#!/usr/bin/env python3
"""Build curriculum.js — run once, then delete this script."""
import json

CURRICULUM = [
  {
    "id": 1, "level": "A2", "title": "Present Simple & Continuous",
    "titleRu": "Настоящее простое и длительное время", "topic": "Рутина и действие сейчас",
    "description": "Учимся различать постоянные действия и то, что происходит в данный момент. Это база для ежедневного общения на английском.",
    "duration": "20 мин",
    "warmup": ["What do you usually do on weekdays?", "What are you doing right now?", "How often do you study English?"],
    "vocab": [{"en":"routine","ru":"распорядок дня"},{"en":"usually","ru":"обычно"},{"en":"currently","ru":"в настоящее время"},{"en":"habit","ru":"привычка"},{"en":"schedule","ru":"расписание"},{"en":"daily","ru":"ежедневный"},{"en":"moment","ru":"момент"},{"en":"often","ru":"часто"},{"en":"rarely","ru":"редко"},{"en":"always","ru":"всегда"}],
    "grammar": {"title":"Present Simple & Present Continuous","blocks":[{"title":"Present Simple","desc":"Используем для привычек, фактов и регулярных действий. Маркеры: every day, usually, often, always.","example":"She works from home on Fridays."},{"title":"Present Continuous","desc":"Используем для действий, происходящих сейчас или временных ситуаций. Маркеры: now, at the moment, right now.","example":"They are watching a documentary at the moment."}],"formulas":["Present Simple: I/you/we/they + V1; he/she/it + V1+s","Present Continuous: am/is/are + V-ing"],"extraExamples":[{"label":"Present Simple","items":["I read books every evening.","He plays tennis on weekends."]},{"label":"Present Continuous","items":["I am reading a book now.","He is playing tennis at the moment."]}],"mistake":{"wrong":"I am go to work every day.","right":"I go to work every day."}},
    "quiz": [{"sentence":"I ___ English every day.","options":["study","am studying"],"answer":"study"},{"sentence":"She ___ TV at the moment.","options":["watches","is watching"],"answer":"is watching"},{"sentence":"We usually ___ dinner at seven.","options":["have","are having"],"answer":"have"},{"sentence":"They ___ football right now.","options":["play","are playing"],"answer":"are playing"},{"sentence":"He ___ to the gym on Mondays.","options":["goes","is going"],"answer":"goes"}],
    "pronunciation": [{"phrase":"I usually walk to work.","ipa":"/ˈjuːʒuəli wɔːk/","tip":"Слово usually — ударение на первый слог, звук /ʒ/ как в «ж»"},{"phrase":"She is reading now.","ipa":"/ʃiː ɪz ˈriːdɪŋ naʊ/","tip":"Сокращение is → 's сливается с reading"},{"phrase":"Do you often travel?","ipa":"/duː juː ˈɒfn ˈtrævl/","tip":"Often — ударение на первый слог, t часто не произносится"},{"phrase":"We are working today.","ipa":"/wiː ɑː ˈwɜːkɪŋ/","tip":"Are + ing: не делай паузу между are и working"},{"phrase":"He always arrives early.","ipa":"/hiː ˈɔːlweɪz əˈraɪvz/","tip":"Always — ударение на первый слог, s звучит как /z/"}],
    "flashcards": [{"word":"routine","trans":"распорядок дня","example":"My daily routine starts at seven."},{"word":"usually","trans":"обычно","example":"I usually wake up early."},{"word":"currently","trans":"в настоящее время","example":"She is currently living in Berlin."},{"word":"habit","trans":"привычка","example":"Reading is a good habit."},{"word":"schedule","trans":"расписание","example":"Check the schedule for tomorrow."},{"word":"daily","trans":"ежедневный","example":"I do daily exercises."},{"word":"moment","trans":"момент","example":"Wait a moment, please."},{"word":"often","trans":"часто","example":"We often meet on Sundays."},{"word":"rarely","trans":"редко","example":"He rarely eats fast food."},{"word":"always","trans":"всегда","example":"She always smiles."},{"word":"work","trans":"работать","example":"I work from nine to five."},{"word":"study","trans":"учиться","example":"They study English every day."},{"word":"read","trans":"читать","example":"He is reading a novel now."},{"word":"watch","trans":"смотреть","example":"We watch films on weekends."},{"word":"play","trans":"играть","example":"The children are playing outside."},{"word":"walk","trans":"ходить пешком","example":"I walk to the park every morning."},{"word":"cook","trans":"готовить","example":"She is cooking dinner now."},{"word":"listen","trans":"слушать","example":"I listen to podcasts often."},{"word":"travel","trans":"путешествовать","example":"They travel every summer."},{"word":"exercise","trans":"заниматься спортом","example":"He exercises three times a week."}],
    "culture": {"watch":["The Crown — британский английский и формальная речь"],"listen":["Adele — Someone Like You"],"read":["Roald Dahl — Charlie and the Chocolate Factory"]},
    "cultureCheck": ["What does the main character usually do in the morning?","What is happening in the scene right now?","How often does the family travel?","What are they watching at the moment?","Does he always arrive on time?"],
    "speaking": ["Опиши свой типичный день, используя 4 предложения в Present Simple.","Расскажи, что ты делаешь прямо сейчас — 3 предложения в Present Continuous.","Сравни свою рутину в будни и выходные, используя оба времени."]
  },
  {
    "id": 2, "level": "A2", "title": "Past Simple & Past Continuous",
    "titleRu": "Прошедшее простое и длительное время", "topic": "Прошлые события и фон",
    "description": "Разбираем, как рассказывать о завершённых действиях в прошлом и описывать фон, на котором они происходили.",
    "duration": "20 мин",
    "warmup": ["What did you do yesterday evening?", "Were you studying when I called?", "Where were you born?"],
    "vocab": [{"en":"yesterday","ru":"вчера"},{"en":"ago","ru":"назад"},{"en":"while","ru":"в то время как"},{"en":"suddenly","ru":"внезапно"},{"en":"finished","ru":"закончил(а)"},{"en":"happened","ru":"произошло"},{"en":"arrived","ru":"прибыл(а)"},{"en":"started","ru":"начал(а)"},{"en":"interrupted","ru":"прервал(а)"},{"en":"background","ru":"фон, задний план"}],
    "grammar": {"title":"Past Simple & Past Continuous","blocks":[{"title":"Past Simple","desc":"Завершённое действие в прошлом с известным временем. Маркеры: yesterday, last week, ago, in 2020.","example":"I visited my grandparents last month."},{"title":"Past Continuous","desc":"Длительное действие в процессе в прошлом или фон для другого события. Маркеры: while, when, at that moment.","example":"She was cooking when the phone rang."}],"formulas":["Past Simple: V2 (regular: V+ed; irregular: 2nd form)","Past Continuous: was/were + V-ing"],"extraExamples":[{"label":"Past Simple","items":["They moved to London in 2019.","He didn't finish the project."]},{"label":"Past Continuous","items":["It was raining all morning.","We were talking when he arrived."]}],"mistake":{"wrong":"I was go to school yesterday.","right":"I went to school yesterday."}},
    "quiz": [{"sentence":"She ___ a letter when I called.","options":["wrote","was writing"],"answer":"was writing"},{"sentence":"We ___ to Paris last summer.","options":["travelled","were travelling"],"answer":"travelled"},{"sentence":"They ___ TV at eight o'clock yesterday.","options":["watched","were watching"],"answer":"were watching"},{"sentence":"He ___ his keys this morning.","options":["lost","was losing"],"answer":"lost"},{"sentence":"While I ___, it started to snow.","options":["walked","was walking"],"answer":"was walking"}],
    "pronunciation": [{"phrase":"I visited London last year.","ipa":"/ˈvɪzɪtɪd ˈlʌndən/","tip":"Visited — ударение на первый слог, ed звучит как /ɪd/"},{"phrase":"She was reading a book.","ipa":"/ʃiː wɒz ˈriːdɪŋ/","tip":"Was — короткий звук /wɒz/, не растягивай"},{"phrase":"What happened yesterday?","ipa":"/wɒt ˈhæpənd/","tip":"Happened — ed как /d/, не /ɪd/"},{"phrase":"They were waiting outside.","ipa":"/ðeɪ wə ˈweɪtɪŋ/","tip":"Were в быстрой речи → /wə/"},{"phrase":"He arrived suddenly.","ipa":"/hiː əˈraɪvd ˈsʌdnli/","tip":"Suddenly — ударение на первый слог"}],
    "flashcards": [{"word":"yesterday","trans":"вчера","example":"I worked yesterday."},{"word":"ago","trans":"назад","example":"She left two hours ago."},{"word":"while","trans":"в то время как","example":"While I slept, he cooked."},{"word":"suddenly","trans":"внезапно","example":"Suddenly, the lights went out."},{"word":"finished","trans":"закончил","example":"I finished my homework."},{"word":"happened","trans":"произошло","example":"What happened last night?"},{"word":"arrived","trans":"прибыл","example":"The train arrived on time."},{"word":"started","trans":"начал","example":"The film started at eight."},{"word":"interrupted","trans":"прервал","example":"Sorry, I interrupted you."},{"word":"background","trans":"фон","example":"Music played in the background."},{"word":"visited","trans":"посетил","example":"We visited the museum."},{"word":"was cooking","trans":"готовил(а)","example":"She was cooking dinner."},{"word":"rang","trans":"звонил (телефон)","example":"The phone rang loudly."},{"word":"moved","trans":"переехал","example":"They moved to a new city."},{"word":"rained","trans":"шёл дождь","example":"It rained all day."},{"word":"waited","trans":"ждал","example":"I waited for an hour."},{"word":"lost","trans":"потерял","example":"He lost his wallet."},{"word":"walked","trans":"шёл","example":"We walked home slowly."},{"word":"called","trans":"позвонил","example":"She called me yesterday."},{"word":"snowed","trans":"шёл снег","example":"It snowed last winter."}],
    "culture": {"watch":["Downton Abbey — исторические события в прошлом"],"listen":["The Beatles — Yesterday"],"read":["Mark Twain — The Adventures of Tom Sawyer"]},
    "cultureCheck": ["What did the character do last weekend?","What was she doing when the event happened?","Where did they travel two years ago?","Was he working when you arrived?","What suddenly happened in the story?"],
    "speaking": ["Расскажи о вчерашнем вечере: 3 предложения в Past Simple.","Опиши ситуацию «я делал X, когда произошло Y» — 2 предложения с Past Continuous.","Расскажи короткую историю из детства, используя оба времени."]
  },
  {
    "id": 3, "level": "A2", "title": "Present Perfect",
    "titleRu": "Настоящее совершённое время", "topic": "Опыт и результат",
    "description": "Present Perfect связывает прошлое с настоящим: опыт, недавние события и результат, важный сейчас.",
    "duration": "20 мин",
    "warmup": ["Have you ever been abroad?", "What have you done today?", "How long have you studied English?"],
    "vocab": [{"en":"ever","ru":"когда-либо"},{"en":"never","ru":"никогда"},{"en":"already","ru":"уже"},{"en":"yet","ru":"ещё (не)"},{"en":"just","ru":"только что"},{"en":"recently","ru":"недавно"},{"en":"experience","ru":"опыт"},{"en":"since","ru":"с (какого-то момента)"},{"en":"for","ru":"в течение"},{"en":"result","ru":"результат"}],
    "grammar": {"title":"Present Perfect","blocks":[{"title":"Опыт и результат","desc":"Используем, когда важен сам факт или результат, а не точное время. Маркеры: ever, never, already, yet, just.","example":"I have finished my homework."},{"title":"For / Since","desc":"For + период времени; since + точка начала. Показывает, как долго действие длится до настоящего.","example":"She has lived here since 2020."}],"formulas":["Affirmative: have/has + V3 (past participle)","Question/Negative: Have/Has + subject + V3 / haven't/hasn't + V3"],"extraExamples":[{"label":"Опыт","items":["Have you ever tried sushi?","I have never seen the ocean."]},{"label":"For/Since","items":["We have known each other for ten years.","He has worked here since March."]}],"mistake":{"wrong":"I have seen him yesterday.","right":"I saw him yesterday."}},
    "quiz": [{"sentence":"She ___ already eaten lunch.","options":["has","have"],"answer":"has"},{"sentence":"___ you ever been to Japan?","options":["Have","Did"],"answer":"Have"},{"sentence":"I ___ my keys. I can't find them.","options":["have lost","lost"],"answer":"have lost"},{"sentence":"We ___ here for three years.","options":["have lived","lived"],"answer":"have lived"},{"sentence":"He hasn't finished ___.","options":["yet","already"],"answer":"yet"}],
    "pronunciation": [{"phrase":"I have finished my work.","ipa":"/aɪ hæv ˈfɪnɪʃt/","tip":"Have часто сокращается до /əv/ или /v/ после местоимений"},{"phrase":"Have you ever been there?","ipa":"/hæv juː ˈevə biːn/","tip":"Ever — ударение на первый слог, короткий звук"},{"phrase":"She has just arrived.","ipa":"/ʃiːz dʒʌst əˈraɪvd/","tip":"Has just → she's just в быстрой речи"},{"phrase":"I haven't seen him yet.","ipa":"/aɪ ˈhævnt siːn/","tip":"Haven't — ударение на haven't, не на seen"},{"phrase":"We've known each other for years.","ipa":"/wiːv nəʊn/","tip":"We've — сокращение we have, known — silent k"}],
    "flashcards": [{"word":"ever","trans":"когда-либо","example":"Have you ever tried climbing?"},{"word":"never","trans":"никогда","example":"I have never been to Australia."},{"word":"already","trans":"уже","example":"She has already left."},{"word":"yet","trans":"ещё (не)","example":"I haven't eaten yet."},{"word":"just","trans":"только что","example":"He has just called."},{"word":"recently","trans":"недавно","example":"I have recently started yoga."},{"word":"experience","trans":"опыт","example":"Travel gives you great experience."},{"word":"since","trans":"с (момента)","example":"I have lived here since 2018."},{"word":"for","trans":"в течение","example":"She has worked here for five years."},{"word":"result","trans":"результат","example":"The result is positive."},{"word":"finished","trans":"закончил","example":"I have finished the book."},{"word":"been","trans":"был (PP of be)","example":"I have been to Rome twice."},{"word":"seen","trans":"видел (PP)","example":"Have you seen this film?"},{"word":"done","trans":"сделал (PP)","example":"I have done my best."},{"word":"known","trans":"знал (PP)","example":"We have known them for years."},{"word":"lost","trans":"потерял (PP)","example":"I have lost my phone."},{"word":"found","trans":"нашёл (PP)","example":"She has found a new job."},{"word":"written","trans":"написал (PP)","example":"He has written three novels."},{"word":"travelled","trans":"путешествовал (PP)","example":"They have travelled widely."},{"word":"learned","trans":"выучил (PP)","example":"I have learned a lot."}],
    "culture": {"watch":["Eat Pray Love — путешествия и личный опыт"],"listen":["U2 — I Still Haven't Found What I'm Looking For"],"read":["J.K. Rowling — Harry Potter and the Philosopher's Stone"]},
    "cultureCheck": ["Has the character ever lived abroad?","What has she just discovered?","How long have they been friends?","Have you ever read this author?","What has happened in the story so far?"],
    "speaking": ["Расскажи о 3 вещах, которые ты когда-либо делал (Have you ever...?).","Опиши, что ты уже сделал сегодня — 4 предложения в Present Perfect.","Скажи, как долго ты занимаешься чем-то (for/since) — 2 предложения."]
  },
  {
    "id": 4, "level": "A2", "title": "Present Perfect vs Past Simple",
    "titleRu": "Present Perfect и Past Simple", "topic": "Когда какое время",
    "description": "Учимся выбирать правильное время: Past Simple для конкретного прошлого, Present Perfect для связи с настоящим.",
    "duration": "20 мин",
    "warmup": ["What did you do last weekend?", "Have you done anything interesting this week?", "When did you start learning English?"],
    "vocab": [{"en":"last","ru":"прошлый"},{"en":"this week","ru":"на этой неделе"},{"en":"specific","ru":"конкретный"},{"en":"unfinished","ru":"незавершённый"},{"en":"connection","ru":"связь"},{"en":"time marker","ru":"маркер времени"},{"en":"recent","ru":"недавний"},{"en":"definite","ru":"определённый"},{"en":"indefinite","ru":"неопределённый"},{"en":"context","ru":"контекст"}],
    "grammar": {"title":"Present Perfect vs Past Simple","blocks":[{"title":"Past Simple","desc":"Конкретное время в прошлом, которое уже закончилось. Маркеры: yesterday, last year, in 2019, ago.","example":"I met her in 2022."},{"title":"Present Perfect","desc":"Без точного времени или связь с настоящим. Маркеры: ever, never, already, yet, this week, so far.","example":"I have met many interesting people."}],"formulas":["Past Simple: V2 + time marker (yesterday, last week)","Present Perfect: have/has + V3 (no specific past time)"],"extraExamples":[{"label":"Past Simple","items":["She left an hour ago.","Did you watch the match last night?"]},{"label":"Present Perfect","items":["She has already left.","Have you watched the new series yet?"]}],"mistake":{"wrong":"I have visited Paris in 2019.","right":"I visited Paris in 2019."}},
    "quiz": [{"sentence":"I ___ him yesterday.","options":["saw","have seen"],"answer":"saw"},{"sentence":"She ___ three countries this year.","options":["visited","has visited"],"answer":"has visited"},{"sentence":"___ you ___ the news last night?","options":["Did / watch","Have / watched"],"answer":"Did / watch"},{"sentence":"We ___ each other since school.","options":["have known","knew"],"answer":"have known"},{"sentence":"He ___ his phone two days ago.","options":["lost","has lost"],"answer":"lost"}],
    "pronunciation": [{"phrase":"I saw him yesterday.","ipa":"/aɪ sɔː hɪm ˈjestədeɪ/","tip":"Saw — неправильный глагол, ударение на yesterday"},{"phrase":"I have seen him recently.","ipa":"/aɪ hæv siːn ˈriːsntli/","tip":"Seen — длинный звук /iː/, silent ee"},{"phrase":"Did you go last week?","ipa":"/dɪd juː ɡəʊ lɑːst wiːk/","tip":"Did — короткий /ɪ/, не растягивай"},{"phrase":"Have you been there before?","ipa":"/hæv juː biːn ðeə/","tip":"Been — один слог /biːn/, не би-эн"},{"phrase":"She left an hour ago.","ipa":"/ʃiː left ən aʊə əˈɡəʊ/","tip":"Ago — ударение на второй слог"}],
    "flashcards": [{"word":"last","trans":"прошлый","example":"I saw her last Monday."},{"word":"this week","trans":"на этой неделе","example":"I have worked hard this week."},{"word":"specific","trans":"конкретный","example":"Give a specific date."},{"word":"unfinished","trans":"незавершённый","example":"This week is unfinished."},{"word":"connection","trans":"связь","example":"Present Perfect shows a connection to now."},{"word":"time marker","trans":"маркер времени","example":"Yesterday is a Past Simple marker."},{"word":"recent","trans":"недавний","example":"I have read a recent article."},{"word":"definite","trans":"определённый","example":"Last year is a definite time."},{"word":"indefinite","trans":"неопределённый","example":"Ever refers to indefinite time."},{"word":"context","trans":"контекст","example":"Context helps choose the tense."},{"word":"saw","trans":"видел (Past Simple)","example":"I saw the film last night."},{"word":"have seen","trans":"видел (Present Perfect)","example":"I have seen that film before."},{"word":"went","trans":"ходил","example":"We went to the beach yesterday."},{"word":"have gone","trans":"сходил/ушёл","example":"She has gone to the shop."},{"word":"met","trans":"встретил","example":"I met him in 2020."},{"word":"have met","trans":"встречал","example":"I have met many teachers."},{"word":"ago","trans":"назад","example":"He called two hours ago."},{"word":"so far","trans":"до сих пор","example":"So far, I have learned 500 words."},{"word":"yet","trans":"ещё","example":"Have you finished yet?"},{"word":"already","trans":"уже","example":"I have already eaten."}],
    "culture": {"watch":["Forrest Gump — события в разные периоды жизни"],"listen":["Frank Sinatra — My Way"],"read":["Agatha Christie — Murder on the Orient Express"]},
    "cultureCheck": ["When did the story begin?","Has the detective found any clues yet?","What happened last chapter?","Have the characters ever met before?","Did she leave yesterday or today?"],
    "speaking": ["Расскажи о прошлых выходных (Past Simple) и о этой неделе (Present Perfect) — по 3 предложения.","Ответь на 5 вопросов Did you...? и Have you ever...?","Объясни по-русски, почему в двух примерах нужны разные времена."]
  },
  {
    "id": 5, "level": "A2", "title": "Future Forms",
    "titleRu": "Формы будущего времени", "topic": "Will, going to, Present Continuous",
    "description": "Три способа говорить о будущем: спонтанные решения, планы и договорённости на ближайшее время.",
    "duration": "20 мин",
    "warmup": ["What are your plans for the weekend?", "What do you think will happen in technology?", "Are you doing anything special tomorrow?"],
    "vocab": [{"en":"plan","ru":"план"},{"en":"prediction","ru":"предсказание"},{"en":"intention","ru":"намерение"},{"en":"appointment","ru":"встреча, назначение"},{"en":"spontaneous","ru":"спонтанный"},{"en":"schedule","ru":"расписание"},{"en":"probably","ru":"вероятно"},{"en":"definitely","ru":"определённо"},{"en":"arrangement","ru":"договорённость"},{"en":"forecast","ru":"прогноз"}],
    "grammar": {"title":"Future: will / going to / Present Continuous","blocks":[{"title":"Will","desc":"Спонтанные решения, предсказания, обещания. Маркеры: I think, probably, maybe.","example":"I think it will rain tomorrow."},{"title":"Going to / Present Continuous","desc":"Going to — планы и намерения; Present Continuous — договорённости с конкретным временем.","example":"I'm going to learn Spanish. / I'm meeting Anna at six."}],"formulas":["Will: will + V1 (won't + V1)","Going to: am/is/are + going to + V1","Future arrangement: am/is/are + V-ing + time"],"extraExamples":[{"label":"Will","items":["Don't worry, I'll help you.","Robots will change many jobs."]},{"label":"Going to / Arrangement","items":["We're going to move next year.","She is flying to Rome on Friday."]}],"mistake":{"wrong":"I will meeting him tomorrow.","right":"I am meeting him tomorrow."}},
    "quiz": [{"sentence":"Look at those clouds! It ___ rain.","options":["will","is going to"],"answer":"is going to"},{"sentence":"I ___ you with your project.","options":["will help","am helping"],"answer":"will help"},{"sentence":"We ___ dinner with friends on Saturday.","options":["will have","are having"],"answer":"are having"},{"sentence":"She ___ a doctor when she grows up.","options":["will be","is being"],"answer":"will be"},{"sentence":"They ___ to Japan next month.","options":["are going to travel","travel"],"answer":"are going to travel"}],
    "pronunciation": [{"phrase":"I will help you.","ipa":"/aɪ wɪl help juː/","tip":"Will — короткий /ɪ/, часто сокращается до I'll"},{"phrase":"It's going to rain.","ipa":"/ɪts ˈɡəʊɪŋ tə reɪn/","tip":"Going to → gonna /ˈɡənə/ в разговорной речи"},{"phrase":"I'm meeting her at six.","ipa":"/aɪm ˈmiːtɪŋ/","tip":"Meeting — двойное t звучит как одно"},{"phrase":"I think it will work.","ipa":"/aɪ θɪŋk ɪt wɪl wɜːk/","tip":"Will work — связывай слова без паузы"},{"phrase":"We're going to move.","ipa":"/wɪə ˈɡəʊɪŋ tə muːv/","tip":"We're — /wɪə/, не разделяй на we are"}],
    "flashcards": [{"word":"plan","trans":"план","example":"I plan to travel next summer."},{"word":"prediction","trans":"предсказание","example":"That's just a prediction."},{"word":"intention","trans":"намерение","example":"My intention is to improve."},{"word":"appointment","trans":"встреча","example":"I have a doctor's appointment."},{"word":"spontaneous","trans":"спонтанный","example":"It was a spontaneous decision."},{"word":"schedule","trans":"расписание","example":"Check the train schedule."},{"word":"probably","trans":"вероятно","example":"It will probably snow."},{"word":"definitely","trans":"определённо","example":"I will definitely come."},{"word":"arrangement","trans":"договорённость","example":"We made an arrangement."},{"word":"forecast","trans":"прогноз","example":"The weather forecast looks good."},{"word":"will","trans":"will (будущее)","example":"I will call you later."},{"word":"going to","trans":"собираюсь","example":"She is going to study abroad."},{"word":"I'll","trans":"я (сделаю)","example":"I'll send the email."},{"word":"won't","trans":"не буду","example":"He won't be late."},{"word":"promise","trans":"обещание","example":"I promise I will try."},{"word":"tonight","trans":"сегодня вечером","example":"I'm working tonight."},{"word":"tomorrow","trans":"завтра","example":"We are leaving tomorrow."},{"word":"next week","trans":"на следующей неделе","example":"I'm going to start next week."},{"word":"maybe","trans":"может быть","example":"Maybe it will be sunny."},{"word":"future","trans":"будущее","example":"The future is uncertain."}],
    "culture": {"watch":["Back to the Future — предсказания о будущем"],"listen":["Louis Armstrong — What a Wonderful World"],"read":["George Orwell — 1984"]},
    "cultureCheck": ["What will probably happen next in the story?","What is the character going to do tomorrow?","Are they meeting anyone this weekend?","What did he promise he would do?","What are your predictions for the ending?"],
    "speaking": ["Опиши свои планы на выходные, используя going to и Present Continuous.","Сделай 3 предсказания о будущем с will.","Ролевая игра: друг просит помощи — ответь спонтанно с I'll..."]
  },
]

import os
script_dir = os.path.dirname(os.path.abspath(__file__))
chunks_path = os.path.join(script_dir, '_curriculum_chunks.json')
if os.path.exists(chunks_path):
    with open(chunks_path) as f:
        CURRICULUM.extend(json.load(f))

assert len(CURRICULUM) == 20, f"Expected 20 lessons, got {len(CURRICULUM)}"

out = os.path.join(script_dir, 'curriculum.js')
with open(out, 'w', encoding='utf-8') as f:
    f.write('const CURRICULUM = ')
    json.dump(CURRICULUM, f, ensure_ascii=False, indent=2)
    f.write(';\n')

print(f"Wrote {out} with {len(CURRICULUM)} lessons")
