"""Authoritative content for filler modules 9–16, 25–32, 41–48, 57–64."""

FILLER_IDS = list(range(9, 17)) + list(range(25, 33)) + list(range(41, 49)) + list(range(57, 65))


def _L(
    topic_en,
    description,
    warmup,
    vocab,
    grammar_title,
    blocks,
    formulas,
    mistake,
    quiz,
    pronunciation,
    culture,
    culture_check,
    speaking,
    extra_examples=None,
):
    return {
        "topic": topic_en,
        "description": description,
        "warmup": warmup,
        "vocab": vocab,
        "grammar": {
            "title": grammar_title,
            "blocks": blocks,
            "formulas": formulas,
            "extraExamples": extra_examples
            or [{"label": "Examples", "items": [b["example"] for b in blocks]}],
            "mistake": mistake,
        },
        "quiz": quiz,
        "pronunciation": pronunciation,
        "culture": culture,
        "cultureCheck": culture_check,
        "speaking": speaking,
    }


FILLER = {
    9: _L(
        "Family members",
        "Talk about your family: parents, siblings, and possessive adjectives.",
        [
            "How many people are in your family?",
            "Do you have any brothers or sisters?",
            "Where do your parents live?",
        ],
        [
            {"en": "mother", "ru": "мать"},
            {"en": "father", "ru": "отец"},
            {"en": "sister", "ru": "сестра"},
            {"en": "brother", "ru": "брат"},
            {"en": "son", "ru": "сын"},
            {"en": "daughter", "ru": "дочь"},
            {"en": "parents", "ru": "родители"},
            {"en": "husband", "ru": "муж"},
            {"en": "wife", "ru": "жена"},
            {"en": "family", "ru": "семья"},
        ],
        "Family",
        [
            {
                "title": "Family members",
                "desc": "Mother, father, brother, sister, son, daughter, parents.",
                "example": "My parents live in Moscow.",
            },
            {
                "title": "Possessives",
                "desc": "Use my, your, his, her, their before a noun.",
                "example": "Her brother is a teacher.",
            },
        ],
        ["my/your/his/her + family member", "have + number + brothers/sisters"],
        {"wrong": "I have two brother.", "right": "I have two brothers."},
        [
            {"sentence": "My ___ is a doctor.", "options": ["mother", "mothers"], "answer": "mother"},
            {"sentence": "They have two ___.", "options": ["children", "childs"], "answer": "children"},
            {"sentence": "___ parents are retired.", "options": ["Her", "She"], "answer": "Her"},
            {"sentence": "Do you have any ___?", "options": ["sisters", "sister"], "answer": "sisters"},
            {"sentence": "His ___ works abroad.", "options": ["wife", "wifes"], "answer": "wife"},
        ],
        [
            {"phrase": "My parents live in Moscow.", "ipa": "/maɪ ˈpeərənts lɪv ɪn ˈmɒskəʊ/", "tip": "Parents — stress on the first syllable"},
            {"phrase": "I have two brothers.", "ipa": "/aɪ hæv tuː ˈbrʌðəz/", "tip": "Brothers — voiced /ð/"},
            {"phrase": "Her sister is younger.", "ipa": "/hɜː ˈsɪstə ɪz ˈjʌŋɡə/", "tip": "Her sister — link the words smoothly"},
            {"phrase": "We are a big family.", "ipa": "/wiː ɑː ə bɪɡ ˈfæməli/", "tip": "Family — stress on fam-" },
            {"phrase": "My husband and I.", "ipa": "/maɪ ˈhʌzbənd ənd aɪ/", "tip": "Husband — silent h in some accents, keep it clear"},
        ],
        {
            "watch": ["Modern Family — season 1, episode 1"],
            "listen": ["Ed Sheeran — Photograph"],
            "read": ["Oxford Bookworms — The Elephant Man (family theme)"],
        },
        [
            "How many people are in the family?",
            "Who is the oldest child?",
            "Where do the parents live?",
            "What does her brother do?",
            "How do they describe their family?",
        ],
        [
            "Опиши свою семью: 5 предложений с my/his/her.",
            "Скажи, сколько у тебя братьев и сестёр.",
            "Задай 3 вопроса о семье собеседника.",
        ],
    ),
    10: _L(
        "Food and drinks",
        "Order food, talk about meals, and use countable food words naturally.",
        [
            "What do you usually eat for breakfast?",
            "Do you prefer tea or coffee?",
            "What is your favourite dish?",
        ],
        [
            {"en": "breakfast", "ru": "завтрак"},
            {"en": "lunch", "ru": "обед"},
            {"en": "dinner", "ru": "ужин"},
            {"en": "water", "ru": "вода"},
            {"en": "coffee", "ru": "кофе"},
            {"en": "tea", "ru": "чай"},
            {"en": "bread", "ru": "хлеб"},
            {"en": "chicken", "ru": "курица"},
            {"en": "salad", "ru": "салат"},
            {"en": "hungry", "ru": "голодный"},
        ],
        "Food & drinks",
        [
            {
                "title": "Meals",
                "desc": "Have breakfast/lunch/dinner. For breakfast I usually have…",
                "example": "I usually have eggs and toast for breakfast.",
            },
            {
                "title": "Ordering",
                "desc": "I'd like… / Can I have…? / A table for two, please.",
                "example": "Can I have a coffee, please?",
            },
        ],
        ["have + food for breakfast/lunch", "I'd like + noun", "Can I have + noun?"],
        {"wrong": "I want a waters.", "right": "I want some water."},
        [
            {"sentence": "I'd like a ___, please.", "options": ["coffee", "coffees"], "answer": "coffee"},
            {"sentence": "She ___ lunch at one.", "options": ["has", "have"], "answer": "has"},
            {"sentence": "Are you ___?", "options": ["hungry", "hungrily"], "answer": "hungry"},
            {"sentence": "We need some ___.", "options": ["bread", "breads"], "answer": "bread"},
            {"sentence": "What do you ___ for breakfast?", "options": ["have", "has"], "answer": "have"},
        ],
        [
            {"phrase": "Can I have a coffee, please?", "ipa": "/kən aɪ hæv ə ˈkɒfi pliːz/", "tip": "Polite requests use please at the end"},
            {"phrase": "I'm hungry.", "ipa": "/aɪm ˈhʌŋɡri/", "tip": "Hungry — stress on hun-" },
            {"phrase": "I'd like the chicken salad.", "ipa": "/aɪd laɪk ðə ˈtʃɪkɪn ˈsæləd/", "tip": "I'd like — common in cafés"},
            {"phrase": "A table for two, please.", "ipa": "/ə ˈteɪbl fɔː tuː pliːz/", "tip": "Table for two — fixed phrase"},
            {"phrase": "The bill, please.", "ipa": "/ðə bɪl pliːz/", "tip": "Bill (BrE) = check (AmE)"},
        ],
        {
            "watch": ["Chef's Table — season 1 (food vocabulary)"],
            "listen": ["Louis Armstrong — What a Wonderful World"],
            "read": ["Penguin Readers A1 — The Fisherman and His Soul"],
        },
        [
            "What does the character order?",
            "What do they eat for breakfast?",
            "Do they prefer tea or coffee?",
            "Is anyone hungry in the scene?",
            "What polite phrase do they use?",
        ],
        [
            "Опиши свой обычный завтрак — 4 предложения.",
            "Сыграй заказ в кафе: Can I have…?",
            "Назови 5 любимых блюд и напитков.",
        ],
    ),
    11: _L(
        "Colours and clothes",
        "Describe what people wear using colours and common clothing words.",
        [
            "What colour is your favourite jacket?",
            "What are you wearing today?",
            "Do you prefer casual or formal clothes?",
        ],
        [
            {"en": "red", "ru": "красный"},
            {"en": "blue", "ru": "синий"},
            {"en": "black", "ru": "чёрный"},
            {"en": "white", "ru": "белый"},
            {"en": "shirt", "ru": "рубашка"},
            {"en": "dress", "ru": "платье"},
            {"en": "jeans", "ru": "джинсы"},
            {"en": "jacket", "ru": "куртка"},
            {"en": "shoes", "ru": "обувь"},
            {"en": "wear", "ru": "носить (одежду)"},
        ],
        "Colours & clothes",
        [
            {
                "title": "Colours",
                "desc": "What colour is…? It is + colour. My bag is blue.",
                "example": "Her dress is red.",
            },
            {
                "title": "Clothes",
                "desc": "Wear + clothes. She is wearing a black jacket.",
                "example": "I wear jeans to work.",
            },
        ],
        ["What colour is + noun?", "I am wearing + clothes", "She wears + clothes"],
        {"wrong": "I am wear a hat.", "right": "I am wearing a hat."},
        [
            {"sentence": "She is ___ a blue dress.", "options": ["wearing", "wear"], "answer": "wearing"},
            {"sentence": "My shoes are ___.", "options": ["black", "blacks"], "answer": "black"},
            {"sentence": "What ___ is your bag?", "options": ["colour", "colours"], "answer": "colour"},
            {"sentence": "He ___ a white shirt.", "options": ["wears", "wear"], "answer": "wears"},
            {"sentence": "These ___ are new.", "options": ["jeans", "jean"], "answer": "jeans"},
        ],
        [
            {"phrase": "What colour is your bag?", "ipa": "/wɒt ˈkʌlə ɪz jɔː bæɡ/", "tip": "Colour (BrE) / color (AmE)"},
            {"phrase": "I'm wearing a black jacket.", "ipa": "/aɪm ˈweərɪŋ ə blæk ˈdʒækɪt/", "tip": "Wearing — continuous for clothes now"},
            {"phrase": "She wears jeans every day.", "ipa": "/ʃiː weəz dʒiːnz ˈevri deɪ/", "tip": "Jeans — always plural"},
            {"phrase": "These shoes are too big.", "ipa": "/ðiːz ʃuːz ə tuː bɪɡ/", "tip": "These + plural noun"},
            {"phrase": "I need a new shirt.", "ipa": "/aɪ niːd ə njuː ʃɜːt/", "tip": "Shirt — clear /ʃ/ sound"},
        ],
        {
            "watch": ["The Devil Wears Prada — fashion scenes"],
            "listen": ["Madonna — Vogue"],
            "read": ["Graded reader — shopping for clothes dialogues"],
        },
        [
            "What colour is the main character's outfit?",
            "What is she wearing in the scene?",
            "Does he prefer casual clothes?",
            "What clothes are mentioned?",
            "Are the shoes new or old?",
        ],
        [
            "Опиши свой наряд сегодня — 4 предложения.",
            "Опиши одежду друга: colours + clothes.",
            "Сравни formal and casual clothes — 3 предложения.",
        ],
    ),
    12: _L(
        "Weather and seasons",
        "Talk about the weather today and typical seasons in your country.",
        [
            "What's the weather like today?",
            "Which season do you like best?",
            "Is it colder in winter where you live?",
        ],
        [
            {"en": "sunny", "ru": "солнечно"},
            {"en": "rainy", "ru": "дождливо"},
            {"en": "cold", "ru": "холодно"},
            {"en": "hot", "ru": "жарко"},
            {"en": "windy", "ru": "ветрено"},
            {"en": "snow", "ru": "снег"},
            {"en": "spring", "ru": "весна"},
            {"en": "summer", "ru": "лето"},
            {"en": "autumn", "ru": "осень"},
            {"en": "winter", "ru": "зима"},
        ],
        "Weather",
        [
            {
                "title": "Today's weather",
                "desc": "What's the weather like? It's sunny/rainy/cold.",
                "example": "It's rainy today.",
            },
            {
                "title": "Seasons",
                "desc": "In summer it is hot. In winter it is cold.",
                "example": "In winter it often snows here.",
            },
        ],
        ["It's + weather adjective", "In + season + it is…"],
        {"wrong": "It is sun today.", "right": "It is sunny today."},
        [
            {"sentence": "It's ___ today.", "options": ["windy", "wind"], "answer": "windy"},
            {"sentence": "In summer it is usually ___.", "options": ["hot", "hotly"], "answer": "hot"},
            {"sentence": "It often ___ in winter.", "options": ["snows", "snow"], "answer": "snows"},
            {"sentence": "___ the weather like?", "options": ["What's", "How's"], "answer": "What's"},
            {"sentence": "I love ___ because the leaves are beautiful.", "options": ["autumn", "autumns"], "answer": "autumn"},
        ],
        [
            {"phrase": "It's sunny today.", "ipa": "/ɪts ˈsʌni təˈdeɪ/", "tip": "It's — common spoken form"},
            {"phrase": "It's raining.", "ipa": "/ɪts ˈreɪnɪŋ/", "tip": "Raining — continuous for weather now"},
            {"phrase": "In winter it is cold.", "ipa": "/ɪn ˈwɪntə ɪt ɪz kəʊld/", "tip": "In winter — no the before seasons"},
            {"phrase": "Which season do you prefer?", "ipa": "/wɪtʃ ˈsiːzn də juː prɪˈfɜː/", "tip": "Prefer — stress on -fer"},
            {"phrase": "It often snows here.", "ipa": "/ɪt ˈɒfn snəʊz hɪə/", "tip": "Snows — verb for weather"},
        ],
        {
            "watch": ["BBC Weather forecast clips"],
            "listen": ["Frank Sinatra — Fly Me to the Moon"],
            "read": ["National Geographic Kids — seasons"],
        },
        [
            "What is the weather like in the scene?",
            "Which season is it?",
            "Is it hot or cold?",
            "Does it rain or snow?",
            "What season does the speaker prefer?",
        ],
        [
            "Опиши погоду сегодня — 3 предложения.",
            "Расскажи о четырёх сезонах в твоём городе.",
            "Спроси у партнёра: What's the weather like?",
        ],
    ),
    13: _L(
        "Shopping",
        "Ask about prices and pay in shops using natural phrases.",
        [
            "How much does your phone cost?",
            "Do you usually pay by card or in cash?",
            "Where do you usually go shopping?",
        ],
        [
            {"en": "price", "ru": "цена"},
            {"en": "cheap", "ru": "дешёвый"},
            {"en": "expensive", "ru": "дорогой"},
            {"en": "cash", "ru": "наличные"},
            {"en": "card", "ru": "карта"},
            {"en": "receipt", "ru": "чек"},
            {"en": "discount", "ru": "скидка"},
            {"en": "size", "ru": "размер"},
            {"en": "try on", "ru": "примерять"},
            {"en": "change", "ru": "сдача"},
        ],
        "Shopping",
        [
            {
                "title": "Prices",
                "desc": "How much is it? It costs ten pounds. That's expensive.",
                "example": "How much is this shirt?",
            },
            {
                "title": "Paying",
                "desc": "Pay by card / in cash. Can I pay by card?",
                "example": "I'll pay by card, please.",
            },
        ],
        ["How much is + noun?", "It costs + price", "pay by card / in cash"],
        {"wrong": "How much cost this?", "right": "How much does this cost?"},
        [
            {"sentence": "How much ___ this jacket?", "options": ["is", "are"], "answer": "is"},
            {"sentence": "It ___ twenty pounds.", "options": ["costs", "cost"], "answer": "costs"},
            {"sentence": "Can I ___ by card?", "options": ["pay", "pays"], "answer": "pay"},
            {"sentence": "This is too ___.", "options": ["expensive", "expensively"], "answer": "expensive"},
            {"sentence": "Do you have a ___?", "options": ["receipt", "receipts"], "answer": "receipt"},
        ],
        [
            {"phrase": "How much is this?", "ipa": "/haʊ mʌtʃ ɪz ðɪs/", "tip": "Fixed shopping phrase"},
            {"phrase": "I'll pay by card.", "ipa": "/aɪl peɪ baɪ kɑːd/", "tip": "By card — no the"},
            {"phrase": "Do you take cash?", "ipa": "/də juː teɪk kæʃ/", "tip": "Take cash — natural in shops"},
            {"phrase": "Can I try it on?", "ipa": "/kən aɪ traɪ ɪt ɒn/", "tip": "Try on — phrasal verb"},
            {"phrase": "That's too expensive.", "ipa": "/ðæts tuː ɪkˈspensɪv/", "tip": "Too + adjective"},
        ],
        {
            "watch": ["Superstore — season 1 (shopping scenes)"],
            "listen": ["ABBA — Money, Money, Money"],
            "read": ["English File A1 — at the shop dialogues"],
        },
        [
            "How much does the item cost?",
            "Do they pay by card or cash?",
            "Is the product cheap or expensive?",
            "What size do they ask for?",
            "Do they get a receipt?",
        ],
        [
            "Сыграй диалог в магазине: price + payment.",
            "Опиши последнюю покупку — 4 предложения.",
            "Сравни два товара: cheap vs expensive.",
        ],
    ),
    14: _L(
        "Directions",
        "Ask for and give directions using prepositions of place.",
        [
            "Where is the nearest café?",
            "How do you get to the station?",
            "Is there a pharmacy near here?",
        ],
        [
            {"en": "left", "ru": "налево"},
            {"en": "right", "ru": "направо"},
            {"en": "straight", "ru": "прямо"},
            {"en": "near", "ru": "рядом"},
            {"en": "next to", "ru": "рядом с"},
            {"en": "opposite", "ru": "напротив"},
            {"en": "corner", "ru": "угол"},
            {"en": "map", "ru": "карта"},
            {"en": "turn", "ru": "поворачивать"},
            {"en": "block", "ru": "квартал"},
        ],
        "Directions",
        [
            {
                "title": "Asking",
                "desc": "Where is…? How do I get to…? Is there a… near here?",
                "example": "Where is the nearest bank?",
            },
            {
                "title": "Giving directions",
                "desc": "Go straight, turn left, it's next to the park.",
                "example": "Turn right at the corner.",
            },
        ],
        ["Where is + place?", "Turn left/right", "next to / opposite / near"],
        {"wrong": "Turn to left.", "right": "Turn left."},
        [
            {"sentence": "Turn ___ at the traffic lights.", "options": ["left", "the left"], "answer": "left"},
            {"sentence": "The café is ___ the bank.", "options": ["next to", "next"], "answer": "next to"},
            {"sentence": "Go ___ for two blocks.", "options": ["straight", "straightly"], "answer": "straight"},
            {"sentence": "Is there a shop ___ here?", "options": ["near", "nearly"], "answer": "near"},
            {"sentence": "How do I ___ to the station?", "options": ["get", "go"], "answer": "get"},
        ],
        [
            {"phrase": "Turn left at the corner.", "ipa": "/tɜːn left ət ðə ˈkɔːnə/", "tip": "Turn left — no the before left"},
            {"phrase": "Go straight ahead.", "ipa": "/ɡəʊ streɪt əˈhed/", "tip": "Straight ahead — fixed phrase"},
            {"phrase": "It's opposite the park.", "ipa": "/ɪts ˈɒpəzɪt ðə pɑːk/", "tip": "Opposite — stress on pos-" },
            {"phrase": "Where is the nearest station?", "ipa": "/weə ɪz ðə ˈnɪərɪst ˈsteɪʃn/", "tip": "Nearest — superlative"},
            {"phrase": "Is there a pharmacy near here?", "ipa": "/ɪz ðeər ə ˈfɑːməsi nɪə hɪə/", "tip": "Near here — common question"},
        ],
        {
            "watch": ["Rick Steves Europe — asking directions clips"],
            "listen": ["The Proclaimers — I'm Gonna Be (500 Miles)"],
            "read": ["City map reading tasks A1–A2"],
        },
        [
            "Where does the person want to go?",
            "Do they turn left or right?",
            "What landmark is mentioned?",
            "Is the place near or far?",
            "What preposition of place is used?",
        ],
        [
            "Объясни дорогу от дома до станции — 5 шагов.",
            "Спроси: Where is the nearest…?",
            "Нарисуй карту и опиши 3 места с next to/opposite.",
        ],
    ),
    15: _L(
        "Hobbies and free time",
        "Talk about what you enjoy doing in your free time.",
        [
            "What do you do in your free time?",
            "How often do you play sports?",
            "Do you enjoy reading or watching films?",
        ],
        [
            {"en": "hobby", "ru": "хобби"},
            {"en": "music", "ru": "музыка"},
            {"en": "sport", "ru": "спорт"},
            {"en": "read", "ru": "читать"},
            {"en": "draw", "ru": "рисовать"},
            {"en": "cook", "ru": "готовить"},
            {"en": "travel", "ru": "путешествовать"},
            {"en": "free time", "ru": "свободное время"},
            {"en": "enjoy", "ru": "наслаждаться"},
            {"en": "relax", "ru": "отдыхать"},
        ],
        "Hobbies",
        [
            {
                "title": "Free time",
                "desc": "In my free time I… / I enjoy + -ing",
                "example": "In my free time I play guitar.",
            },
            {
                "title": "Frequency",
                "desc": "How often do you…? Once a week / twice a month.",
                "example": "I go swimming twice a week.",
            },
        ],
        ["In my free time I + V", "I enjoy + V-ing", "How often do you + V?"],
        {"wrong": "I enjoy read books.", "right": "I enjoy reading books."},
        [
            {"sentence": "I enjoy ___ to music.", "options": ["listening", "listen"], "answer": "listening"},
            {"sentence": "She plays tennis ___ a week.", "options": ["twice", "two"], "answer": "twice"},
            {"sentence": "What do you do in your ___ time?", "options": ["free", "freely"], "answer": "free"},
            {"sentence": "He likes ___ books.", "options": ["reading", "read"], "answer": "reading"},
            {"sentence": "They often ___ on weekends.", "options": ["travel", "travels"], "answer": "travel"},
        ],
        [
            {"phrase": "In my free time I read.", "ipa": "/ɪn maɪ friː taɪm aɪ riːd/", "tip": "Free time — fixed collocation"},
            {"phrase": "I enjoy playing football.", "ipa": "/aɪ ɪnˈdʒɔɪ ˈpleɪɪŋ ˈfʊtbɔːl/", "tip": "Enjoy + -ing"},
            {"phrase": "How often do you cook?", "ipa": "/haʊ ˈɒfn də juː kʊk/", "tip": "How often — frequency question"},
            {"phrase": "I relax at home.", "ipa": "/aɪ rɪˈlæks ət həʊm/", "tip": "Relax — stress on -lax"},
            {"phrase": "She loves drawing.", "ipa": "/ʃiː lʌvz ˈdrɔːɪŋ/", "tip": "Love + -ing like enjoy"},
        ],
        {
            "watch": ["Stranger Things — hobbies and free time scenes"],
            "listen": ["Queen — Don't Stop Me Now"],
            "read": ["Teen magazine interviews about hobbies"],
        },
        [
            "What hobby does the character mention?",
            "How often do they play sports?",
            "Do they enjoy reading?",
            "What do they do to relax?",
            "What music do they like?",
        ],
        [
            "Расскажи о своих хобби — 5 предложений.",
            "Спроси партнёра How often do you…?",
            "Сравни два хобби: I enjoy… vs I like to…",
        ],
    ),
    16: _L(
        "Health and the doctor",
        "Describe how you feel and talk about common health problems.",
        [
            "How do you feel today?",
            "What do you do when you are ill?",
            "When did you last see a doctor?",
        ],
        [
            {"en": "headache", "ru": "головная боль"},
            {"en": "fever", "ru": "температура"},
            {"en": "cough", "ru": "кашель"},
            {"en": "ill", "ru": "больной"},
            {"en": "tired", "ru": "уставший"},
            {"en": "doctor", "ru": "врач"},
            {"en": "medicine", "ru": "лекарство"},
            {"en": "hurt", "ru": "болеть"},
            {"en": "better", "ru": "лучше"},
            {"en": "appointment", "ru": "приём у врача"},
        ],
        "Health",
        [
            {
                "title": "How you feel",
                "desc": "I don't feel well. I have a headache. My leg hurts.",
                "example": "I don't feel well today.",
            },
            {
                "title": "At the doctor",
                "desc": "Make an appointment. Take medicine. Get better.",
                "example": "You should rest and drink water.",
            },
        ],
        ["I don't feel well", "I have a + illness", "My + body part + hurts"],
        {"wrong": "I have headache.", "right": "I have a headache."},
        [
            {"sentence": "I have a ___.", "options": ["headache", "headaches"], "answer": "headache"},
            {"sentence": "She doesn't feel ___.", "options": ["well", "goodly"], "answer": "well"},
            {"sentence": "My throat ___.", "options": ["hurts", "hurt"], "answer": "hurts"},
            {"sentence": "He needs to see a ___.", "options": ["doctor", "doctors"], "answer": "doctor"},
            {"sentence": "Take this ___ twice a day.", "options": ["medicine", "medicines"], "answer": "medicine"},
        ],
        [
            {"phrase": "I don't feel well.", "ipa": "/aɪ dəʊnt fiːl wel/", "tip": "Feel well — not feel good formally"},
            {"phrase": "I have a headache.", "ipa": "/aɪ hæv ə ˈhedeɪk/", "tip": "A headache — needs a/an"},
            {"phrase": "My leg hurts.", "ipa": "/maɪ leɡ hɜːts/", "tip": "Hurts — for body pain"},
            {"phrase": "I need to see a doctor.", "ipa": "/aɪ niːd tə siː ə ˈdɒktə/", "tip": "See a doctor — fixed phrase"},
            {"phrase": "I hope you feel better.", "ipa": "/aɪ həʊp juː fiːl ˈbetə/", "tip": "Feel better — common wish"},
        ],
        {
            "watch": ["Grey's Anatomy — simple patient dialogues"],
            "listen": ["The Beatles — With a Little Help from My Friends"],
            "read": ["NHS Easy Read — feeling unwell"],
        },
        [
            "How does the patient feel?",
            "What symptoms do they mention?",
            "What does the doctor recommend?",
            "Do they need medicine?",
            "When do they feel better?",
        ],
        [
            "Опиши, как ты себя чувствуешь — 3 предложения.",
            "Сыграй визит к врачу: symptoms + advice.",
            "Дай совет другу: You should rest / drink water.",
        ],
    ),
}

# ── A2 filler 25–32 ──
FILLER.update({
    25: _L(
        "Passive voice (present)",
        "Describe processes and products with is/are + past participle.",
        ["What languages are spoken in your country?", "Where is your phone made?", "Is English taught at your school?"],
        [{"en":"passive","ru":"пассивный залог"},{"en":"made","ru":"сделанный"},{"en":"spoken","ru":"говоримый"},{"en":"built","ru":"построенный"},{"en":"written","ru":"написанный"},{"en":"used","ru":"используемый"},{"en":"grown","ru":"выращиваемый"},{"en":"sold","ru":"продаваемый"},{"en":"opened","ru":"открытый"},{"en":"called","ru":"называемый"}],
        "Passive Voice (present)",
        [{"title":"Form","desc":"am/is/are + past participle (V3). The focus is on the action or object.","example":"English is spoken here."},{"title":"By-agent","desc":"Add by + person when the agent matters.","example":"This phone is made in China."}],
        ["is/are + V3","is/are + V3 + by + agent"],
        {"wrong":"English is speak here.","right":"English is spoken here."},
        [{"sentence":"English ___ here.","options":["is spoken","is spoke"],"answer":"is spoken"},{"sentence":"These cars ___ in Germany.","options":["are made","are make"],"answer":"are made"},{"sentence":"The shop ___ at nine.","options":["is opened","opens"],"answer":"is opened"},{"sentence":"Rice ___ in Asia.","options":["is grown","is grow"],"answer":"is grown"},{"sentence":"The book was ___ by her.","options":["written","wrote"],"answer":"written"}],
        [{"phrase":"English is spoken here.","ipa":"/ˈɪŋɡlɪʃ ɪz ˈspəʊkən hɪə/","tip":"Spoken — past participle"},{"phrase":"This phone is made in China.","ipa":"/ðɪs fəʊn ɪz meɪd ɪn ˈtʃaɪnə/","tip":"Made — irregular V3"},{"phrase":"Where is it produced?","ipa":"/weər ɪz ɪt prəˈdjuːst/","tip":"Produced — common in passive"},{"phrase":"It is used every day.","ipa":"/ɪt ɪz juːzd ˈevri deɪ/","tip":"Used — /juːzd/ vs /juːst/"},{"phrase":"The door is locked.","ipa":"/ðə dɔːr ɪz lɒkt/","tip":"Locked — state passive"}],
        {"watch":["How It's Made — product manufacturing"],"listen":["Daft Punk — Harder, Better, Faster, Stronger"],"read":["BBC Learning English — passive voice"]},
        ["What language is spoken?","Where is the product made?","Is the shop opened or closed?","Who is the book written by?","What is grown in the region?"],
        ["Опиши 4 вещи, которые производятся в твоей стране.","Преобразуй 3 активных предложения в passive.","Ответь: What languages are spoken in…?"],
    ),
    26: _L(
        "Gerunds and infinitives",
        "Choose enjoy + -ing vs want to + verb naturally.",
        ["What do you enjoy doing at weekends?", "What do you want to learn this year?", "Do you prefer cooking or ordering food?"],
        [{"en":"enjoy","ru":"наслаждаться"},{"en":"want","ru":"хотеть"},{"en":"need","ru":"нуждаться"},{"en":"decide","ru":"решать"},{"en":"plan","ru":"планировать"},{"en":"avoid","ru":"избегать"},{"en":"finish","ru":"заканчивать"},{"en":"hope","ru":"надеяться"},{"en":"learn","ru":"учиться"},{"en":"promise","ru":"обещать"}],
        "Gerunds & infinitives",
        [{"title":"Gerund (-ing)","desc":"After enjoy, finish, avoid, mind: enjoy reading.","example":"I enjoy swimming."},{"title":"Infinitive (to)","desc":"After want, need, decide, plan, hope: want to travel.","example":"She wants to learn Spanish."}],
        ["enjoy/finish/avoid + V-ing","want/need/decide + to + V1"],
        {"wrong":"I enjoy to read.","right":"I enjoy reading."},
        [{"sentence":"I enjoy ___ movies.","options":["watching","to watch"],"answer":"watching"},{"sentence":"He wants ___ abroad.","options":["to study","studying"],"answer":"to study"},{"sentence":"She finished ___ her homework.","options":["doing","to do"],"answer":"doing"},{"sentence":"We decided ___ early.","options":["to leave","leaving"],"answer":"to leave"},{"sentence":"They avoid ___ fast food.","options":["eating","to eat"],"answer":"eating"}],
        [{"phrase":"I enjoy reading.","ipa":"/aɪ ɪnˈdʒɔɪ ˈriːdɪŋ/","tip":"Enjoy + -ing only"},{"phrase":"I want to travel.","ipa":"/aɪ wɒnt tə ˈtrævl/","tip":"Want to + base verb"},{"phrase":"She decided to stay.","ipa":"/ʃiː dɪˈsaɪdɪd tə steɪ/","tip":"Decided to — infinitive"},{"phrase":"He finished cooking.","ipa":"/hiː ˈfɪnɪʃt ˈkʊkɪŋ/","tip":"Finished + -ing"},{"phrase":"We need to hurry.","ipa":"/wiː niːd tə ˈhʌri/","tip":"Need to — obligation"}],
        {"watch":["Julie & Julia — cooking verbs"],"listen":["Adele — Chasing Pavements"],"read":["English Grammar in Use — Unit 53"]},
        ["What does she enjoy doing?","What does he want to do?","Did they finish doing something?","What did they decide to do?","What do they avoid doing?"],
        ["Напиши 5 предложений: enjoy + -ing.","Напиши 5 предложений: want/decide + to.","Расскажи о планах: I want to… / I'm planning to…"],
    ),
    27: _L(
        "Question tags",
        "Confirm information with natural question tags: isn't it?, don't you?",
        ["It's a beautiful day, isn't it?", "You speak English, don't you?", "She doesn't like coffee, does she?"],
        [{"en":"tag","ru":"разделительный вопрос"},{"en":"positive","ru":"положительный"},{"en":"negative","ru":"отрицательный"},{"en":"agree","ru":"соглашаться"},{"en":"confirm","ru":"подтверждать"},{"en":"right","ru":"верно"},{"en":"sure","ru":"уверенный"},{"en":"exactly","ru":"именно"},{"en":"actually","ru":"на самом деле"},{"en":"reply","ru":"отвечать"}],
        "Question tags",
        [{"title":"Rules","desc":"Positive statement → negative tag. Negative statement → positive tag. Use the same auxiliary.","example":"You're tired, aren't you?"},{"title":"Answers","desc":"Yes = you agree. No = you disagree.","example":"It's cold, isn't it? — Yes, it is."}],
        ["positive clause, negative tag?","negative clause, positive tag?"],
        {"wrong":"You are tired, aren't you?","right":"You're tired, aren't you?"},
        [{"sentence":"She is nice, ___ she?","options":["isn't","doesn't"],"answer":"isn't"},{"sentence":"They live here, ___ they?","options":["don't","aren't"],"answer":"don't"},{"sentence":"He can't swim, ___ he?","options":["can","can he"],"answer":"can he"},{"sentence":"It was fun, ___ it?","options":["wasn't","didn't"],"answer":"wasn't"},{"sentence":"You haven't finished, ___ you?","options":["have","have you"],"answer":"have you"}],
        [{"phrase":"It's nice, isn't it?","ipa":"/ɪts naɪs ˈɪznt ɪt/","tip":"Isn't it — very common"},{"phrase":"You're coming, aren't you?","ipa":"/jɔː ˈkʌmɪŋ ɑːnt juː/","tip":"Aren't you — after you're"},{"phrase":"She doesn't know, does she?","ipa":"/ʃiː ˈdʌznt nəʊ dʌz ʃiː/","tip":"Positive tag after negative"},{"phrase":"We can help, can't we?","ipa":"/wiː kən help kɑːnt wiː/","tip":"Can't we — modal tag"},{"phrase":"That was great, wasn't it?","ipa":"/ðæt wɒz ɡreɪt ˈwɒznt ɪt/","tip":"Wasn't it — past tag"}],
        {"watch":["British sitcoms — natural tag questions"],"listen":["Oasis — Don't Look Back in Anger"],"read":["Cambridge A2 — question tags exercises"]},
        ["What tag question do they use?","Do they agree or disagree?","Is the tag positive or negative?","What auxiliary is in the tag?","How does the listener reply?"],
        ["Составь 6 предложений с question tags.","Ответь на 4 tag questions вслух.","Преобразуй утверждения в tag questions."],
    ),
    28: _L(
        "Too and enough",
        "Say when something is excessive or sufficient with too and enough.",
        ["Is your room big enough?", "Is it too cold to go out?", "Do you have enough time today?"],
        [{"en":"too","ru":"слишком"},{"en":"enough","ru":"достаточно"},{"en":"big","ru":"большой"},{"en":"small","ru":"маленький"},{"en":"fast","ru":"быстрый"},{"en":"slow","ru":"медленный"},{"en":"old","ru":"старый"},{"en":"young","ru":"молодой"},{"en":"strong","ru":"сильный"},{"en":"weak","ru":"слабый"}],
        "Too & enough",
        [{"title":"Too","desc":"Too + adjective (+ to + verb): too expensive to buy.","example":"It's too cold to swim."},{"title":"Enough","desc":"Adjective + enough / enough + noun.","example":"The room is big enough for us."}],
        ["too + adj (+ to V)","adj + enough / enough + noun"],
        {"wrong":"He is enough old.","right":"He is old enough."},
        [{"sentence":"It's ___ hot to go out.","options":["too","enough"],"answer":"too"},{"sentence":"She is old ___ to drive.","options":["enough","too"],"answer":"enough"},{"sentence":"We don't have ___ money.","options":["enough","too"],"answer":"enough"},{"sentence":"This coffee is ___ strong for me.","options":["too","enough"],"answer":"too"},{"sentence":"Is the bag big ___?","options":["enough","too"],"answer":"enough"}],
        [{"phrase":"It's too cold today.","ipa":"/ɪts tuː kəʊld təˈdeɪ/","tip":"Too + adjective"},{"phrase":"I'm old enough.","ipa":"/aɪm əʊld ɪˈnʌf/","tip":"Adjective + enough"},{"phrase":"We have enough time.","ipa":"/wiː hæv ɪˈnʌf taɪm/","tip":"Enough + noun"},{"phrase":"It's too late to call.","ipa":"/ɪts tuː leɪt tə kɔːl/","tip":"Too…to — result"},{"phrase":"Is it warm enough?","ipa":"/ɪz ɪt wɔːm ɪˈnʌf/","tip":"Warm enough — question"}],
        {"watch":["Tiny House Nation — big enough / too small"],"listen":["Britney Spears — ...Baby One More Time"],"read":["English File A2 — too/enough"]},
        ["Is it too hot or cold?","Do they have enough money?","Is the room big enough?","What is too expensive?","What is too difficult to do?"],
        ["Опиши 4 ситуации с too…to.","Опиши 4 ситуации с adjective + enough.","Спроси партнёра: Is your flat big enough?"],
    ),
    29: _L(
        "First conditional",
        "Talk about real future possibilities with If + present, will.",
        ["What will you do if it rains tomorrow?", "If you study hard, will you pass?", "What will happen if we miss the bus?"],
        [{"en":"if","ru":"если"},{"en":"will","ru":"буду (future)"},{"en":"unless","ru":"если не"},{"en":"probably","ru":"вероятно"},{"en":"possible","ru":"возможный"},{"en":"happen","ru":"происходить"},{"en":"miss","ru":"опоздать, пропустить"},{"en":"arrive","ru":"прибывать"},{"en":"fail","ru":"провалить"},{"en":"succeed","ru":"преуспеть"}],
        "First conditional",
        [{"title":"Structure","desc":"If + present simple, will + verb. Real and likely future.","example":"If it rains, I will stay home."},{"title":"Variations","desc":"Will can go first: I'll call you if I'm late.","example":"If she studies, she will pass."}],
        ["If + present, will + V1","Unless + present = if not"],
        {"wrong":"If it will rain, I stay home.","right":"If it rains, I will stay home."},
        [{"sentence":"If it ___, we will cancel.","options":["rains","will rain"],"answer":"rains"},{"sentence":"She ___ help you if you ask.","options":["will","would"],"answer":"will"},{"sentence":"If they ___, tell me.","options":["arrive","will arrive"],"answer":"arrive"},{"sentence":"I will be late if I ___ the bus.","options":["miss","will miss"],"answer":"miss"},{"sentence":"If he studies, he ___ pass.","options":["will","would"],"answer":"will"}],
        [{"phrase":"If it rains, I'll stay home.","ipa":"/ɪf ɪt reɪnz aɪl steɪ həʊm/","tip":"If + present, not will"},{"phrase":"If you need help, call me.","ipa":"/ɪf juː niːd help kɔːl miː/","tip":"Imperative in result clause OK"},{"phrase":"She'll pass if she studies.","ipa":"/ʃiːl pɑːs ɪf ʃiː ˈstʌdiz/","tip":"Will clause can be first"},{"phrase":"What will you do if it snows?","ipa":"/wɒt wɪl juː duː ɪf ɪt snəʊz/","tip":"Natural future question"},{"phrase":"Unless you hurry, we'll be late.","ipa":"/ənˈles juː ˈhʌri wiːl biː leɪt/","tip":"Unless = if not"}],
        {"watch":["Weather forecast + plans scenes"],"listen":["Bob Dylan — A Hard Rain's A-Gonna Fall"],"read":["Murphy's Grammar — Unit 38"]},
        ["What will they do if it rains?","Is the result likely?","What happens if they miss the bus?","Does if-clause use present or will?","What will she do if she passes?"],
        ["Составь 5 first conditional предложений о своих планах.","Ответь на If it rains tomorrow, what will you do?","Преобразуй планы друга в if-sentences."],
    ),
    30: _L(
        "Used to",
        "Talk about past habits and states that are no longer true.",
        ["What did you use to do as a child?", "Did you use to live in another city?", "What didn't you use to like?"],
        [{"en":"used to","ru":"раньше (привычка)"},{"en":"childhood","ru":"детство"},{"en":"habit","ru":"привычка"},{"en":"past","ru":"прошлое"},{"en":"now","ru":"сейчас"},{"en":"change","ru":"изменение"},{"en":"remember","ru":"помнить"},{"en":"forget","ru":"забывать"},{"en":"move","ru":"переезжать"},{"en":"grow up","ru":"вырастать"}],
        "Used to",
        [{"title":"Past habits","desc":"Used to + verb for repeated past actions, not now.","example":"I used to play football every day."},{"title":"Negative & questions","desc":"Didn't use to / Did you use to…?","example":"I didn't use to like coffee."}],
        ["used to + V1 (past habit)","didn't use to + V1"],
        {"wrong":"I use to live here.","right":"I used to live here."},
        [{"sentence":"I ___ to live in the country.","options":["used","use"],"answer":"used"},{"sentence":"She didn't ___ to eat fish.","options":["use","used"],"answer":"use"},{"sentence":"___ you use to have long hair?","options":["Did","Do"],"answer":"Did"},{"sentence":"We ___ to walk to school.","options":["used","use"],"answer":"used"},{"sentence":"He ___ to be shy.","options":["used","uses"],"answer":"used"}],
        [{"phrase":"I used to live here.","ipa":"/aɪ juːst tə lɪv hɪə/","tip":"Used to — past only"},{"phrase":"Did you use to play piano?","ipa":"/dɪd juː juːs tə pleɪ piˈænəʊ/","tip":"Did you use — no d on use"},{"phrase":"I didn't use to like it.","ipa":"/aɪ ˈdɪdnt juːs tə laɪk ɪt/","tip":"Didn't use to"},{"phrase":"She used to have long hair.","ipa":"/ʃiː juːst tə hæv lɒŋ heə/","tip":"Past state with used to"},{"phrase":"We used to be neighbours.","ipa":"/wiː juːst tə biː ˈneɪbəz/","tip":"Used to be — past state"}],
        {"watch":["Boyhood — childhood memories"],"listen":["Cat Stevens — Father and Son"],"read":["Graded reader — past habits"]},
        ["What did they use to do?","Where did they use to live?","What didn't they use to like?","Do they still do it now?","What changed?"],
        ["Расскажи о 4 привычках детства (used to).","Сравни: I used to… but now I…","Задай 3 вопроса Did you use to…?"],
    ),
    31: _L(
        "Reflexive pronouns",
        "Use myself, yourself, himself when subject and object are the same.",
        ["How do you relax by yourself?", "Did you hurt yourself?", "Do you live by yourself?"],
        [{"en":"myself","ru":"сам(а)"},{"en":"yourself","ru":"сам(и)"},{"en":"himself","ru":"сам"},{"en":"herself","ru":"сама"},{"en":"itself","ru":"само"},{"en":"ourselves","ru":"сами"},{"en":"themselves","ru":"сами"},{"en":"alone","ru":"один"},{"en":"by yourself","ru":"самостоятельно"},{"en":"each other","ru":"друг друга"}],
        "Reflexive pronouns",
        [{"title":"Reflexive","desc":"Subject = object: I cut myself. She taught herself.","example":"He hurt himself playing football."},{"title":"By myself","desc":"Alone / without help: I live by myself.","example":"I made this cake myself."}],
        ["subject + verb + reflexive","by + reflexive = alone"],
        {"wrong":"She looked at her in the mirror.","right":"She looked at herself in the mirror."},
        [{"sentence":"I cut ___ cooking.","options":["myself","me"],"answer":"myself"},{"sentence":"They enjoyed ___ at the party.","options":["themselves","them"],"answer":"themselves"},{"sentence":"She lives by ___.","options":["herself","her"],"answer":"herself"},{"sentence":"We should be proud of ___.","options":["ourselves","us"],"answer":"ourselves"},{"sentence":"Did you hurt ___?","options":["yourself","you"],"answer":"yourself"}],
        [{"phrase":"I hurt myself.","ipa":"/aɪ hɜːt maɪˈself/","tip":"Myself — reflexive"},{"phrase":"She did it herself.","ipa":"/ʃiː dɪd ɪt hɜːˈself/","tip":"Emphatic herself"},{"phrase":"I live by myself.","ipa":"/aɪ lɪv baɪ maɪˈself/","tip":"By myself = alone"},{"phrase":"Enjoy yourself!","ipa":"/ɪnˈdʒɔɪ jɔːˈself/","tip":"Fixed farewell phrase"},{"phrase":"They help each other.","ipa":"/ðeɪ help iːtʃ ˈʌðə/","tip":"Each other — reciprocal"}],
        {"watch":["Cast Away — by himself theme"],"listen":["Bill Withers — Lean on Me"],"read":["English File A2 — reflexive pronouns"]},
        ["Who hurt themselves?","Do they live by themselves?","What did she teach herself?","Do they help each other?","Is myself used correctly?"],
        ["Расскажи, что ты делаешь сам(а) — 4 предложения.","Отличие: each other vs reflexive — 2 примера.","Опиши день, проведённый by yourself."],
    ),
    32: _L(
        "Travel and hotels",
        "Book rooms, ask for services, and handle travel situations.",
        ["Have you ever booked a hotel online?", "What do you say at hotel check-in?", "Could I have a wake-up call, please?"],
        [{"en":"reservation","ru":"бронирование"},{"en":"booking","ru":"бронь"},{"en":"check in","ru":"регистрироваться"},{"en":"check out","ru":"выезжать"},{"en":"room","ru":"номер"},{"en":"reception","ru":"ресепшен"},{"en":"luggage","ru":"багаж"},{"en":"passport","ru":"паспорт"},{"en":"flight","ru":"рейс"},{"en":"single","ru":"одноместный"}],
        "Travel & hotels",
        [{"title":"Booking","desc":"I'd like to book a room. I have a reservation.","example":"I have a reservation for two nights."},{"title":"At the hotel","desc":"Check in/out. Could I have…? Wake-up call.","example":"Could I have a wake-up call at seven?"}],
        ["I'd like to book…","I have a reservation for…","Could I have + service?"],
        {"wrong":"I have reservation.","right":"I have a reservation."},
        [{"sentence":"I have a ___ for two nights.","options":["reservation","reserve"],"answer":"reservation"},{"sentence":"We need to ___ in at three.","options":["check","checking"],"answer":"check"},{"sentence":"Could I have a ___ call at seven?","options":["wake-up","waking"],"answer":"wake-up"},{"sentence":"My ___ is at gate twelve.","options":["flight","fly"],"answer":"flight"},{"sentence":"A ___ room, please.","options":["double","doubly"],"answer":"double"}],
        [{"phrase":"I have a reservation.","ipa":"/aɪ hæv ə ˌrezəˈveɪʃn/","tip":"Reservation — formal booking"},{"phrase":"I'd like to check in.","ipa":"/aɪd laɪk tə tʃek ɪn/","tip":"Check in — hotel arrival"},{"phrase":"Could I have a wake-up call?","ipa":"/kʊd aɪ hæv ə ˈweɪk ʌp kɔːl/","tip":"Polite hotel request"},{"phrase":"What time is checkout?","ipa":"/wɒt taɪm ɪz ˈtʃekaʊt/","tip":"Checkout — one word noun"},{"phrase":"Where is the reception?","ipa":"/weər ɪz ðə rɪˈsepʃn/","tip":"Reception — hotel desk"}],
        {"watch":["BBC Travel — hotel English"],"listen":["Frank Sinatra — Come Fly with Me"],"read":["English for Tourism — hotel dialogues"]},
        ["Do they have a reservation?","What time is check-in?","What service do they request?","Where is the reception?","What room type do they book?"],
        ["Сыграй check-in в отеле — 6 реплик.","Опиши свой последний отпуск — 5 предложений.","Составь диалог бронирования по телефону."],
    ),
})

# ── B1 filler 41–48 ──
FILLER.update({
    41: _L(
        "Second conditional",
        "Talk about unreal or unlikely present/future situations with If I were…, I would…",
        ["What would you do if you won the lottery?", "If you could live anywhere, where would you go?", "What would you change about your city?"],
        [{"en":"would","ru":"бы (условное)"},{"en":"could","ru":"мог бы"},{"en":"unlikely","ru":"маловероятный"},{"en":"imagine","ru":"представлять"},{"en":"lottery","ru":"лотерея"},{"en":"abroad","ru":"за границей"},{"en":"change","ru":"менять"},{"en":"afford","ru":"позволять себе"},{"en":"dream","ru":"мечта"},{"en":"hypothetical","ru":"гипотетический"}],
        "Second conditional",
        [{"title":"Structure","desc":"If + past simple, would + verb. Unreal present/future.","example":"If I had more time, I would travel more."},{"title":"Were for all persons","desc":"If I were you… (formal/subjunctive). If she were rich…","example":"If I were you, I would accept the offer."}],
        ["If + past, would + V1","If I were + noun, I would…"],
        {"wrong":"If I will have money, I would buy a car.","right":"If I had money, I would buy a car."},
        [{"sentence":"If I ___ rich, I would travel.","options":["were","was"],"answer":"were"},{"sentence":"She would move if she ___ a job abroad.","options":["found","finds"],"answer":"found"},{"sentence":"What would you do if you ___ the lottery?","options":["won","win"],"answer":"won"},{"sentence":"If they ___ harder, they would pass.","options":["studied","study"],"answer":"studied"},{"sentence":"I would help if I ___.","options":["could","can"],"answer":"could"}],
        [{"phrase":"If I were you, I'd wait.","ipa":"/ɪf aɪ wə juː aɪd weɪt/","tip":"If I were — all persons in formal English"},{"phrase":"What would you do?","ipa":"/wɒt wʊd juː duː/","tip":"Would — unreal result"},{"phrase":"If I had time, I'd come.","ipa":"/ɪf aɪ hæd taɪm aɪd kʌm/","tip":"Past in if-clause"},{"phrase":"She would live abroad.","ipa":"/ʃiː wʊd lɪv əˈbrɔːd/","tip":"Would + base verb"},{"phrase":"If they knew, they would help.","ipa":"/ɪf ðeɪ njuː ðeɪ wʊd help/","tip":"Knew — past form"}],
        {"watch":["Sliding Doors — what if scenarios"],"listen":["Beyoncé — If I Were a Boy"],"read":["Murphy — Unit 39 second conditional"]},
        ["What would the character do?","Is the situation real or imaginary?","What would you change if you could?","Does the if-clause use past tense?","What would happen if they won?"],
        ["Напиши 5 second conditional о мечтах.","Ответь: If you could live anywhere…","Дай совет: If I were you, I would…"],
    ),
    42: _L(
        "Third conditional",
        "Talk about imaginary past outcomes with If I had known…, I would have…",
        ["What would you have done differently last year?", "If you had studied more, would you have passed?", "What wouldn't have happened if you had left earlier?"],
        [{"en":"regret","ru":"сожаление"},{"en":"otherwise","ru":"иначе"},{"en":"missed","ru":"пропущенный"},{"en":"opportunity","ru":"возможность"},{"en":"luckily","ru":"к счастью"},{"en":"unfortunately","ru":"к сожалению"},{"en":"outcome","ru":"результат"},{"en":"avoid","ru":"избежать"},{"en":"realise","ru":"понять"},{"en":"differently","ru":"по-другому"}],
        "Third conditional",
        [{"title":"Structure","desc":"If + past perfect, would have + V3. Imaginary past.","example":"If I had known, I would have helped."},{"title":"Regrets","desc":"I wish I had… expresses the same regret.","example":"If she had left earlier, she wouldn't have missed the train."}],
        ["If + had + V3, would have + V3","wouldn't have + V3 if + had + V3"],
        {"wrong":"If I knew, I would have called.","right":"If I had known, I would have called."},
        [{"sentence":"If I ___ earlier, I wouldn't have been late.","options":["had left","left"],"answer":"had left"},{"sentence":"She would have passed if she ___.","options":["had studied","studied"],"answer":"had studied"},{"sentence":"If they had called, we ___ helped.","options":["would have","would"],"answer":"would have"},{"sentence":"What would you have done if you ___?","options":["had known","knew"],"answer":"had known"},{"sentence":"He wouldn't have fallen if he ___ careful.","options":["had been","was"],"answer":"had been"}],
        [{"phrase":"If I had known, I would have come.","ipa":"/ɪf aɪ hæd nəʊn aɪ wʊd hæv kʌm/","tip":"Had known — past perfect"},{"phrase":"She would have helped.","ipa":"/ʃiː wʊd hæv helpt/","tip":"Would have + V3"},{"phrase":"If we had left earlier…","ipa":"/ɪf wiː hæd left ˈɜːliə/","tip":"Earlier — comparative"},{"phrase":"I wouldn't have said that.","ipa":"/aɪ ˈwʊdnt hæv sed ðæt/","tip":"Negative conditional"},{"phrase":"What would you have done?","ipa":"/wɒt wʊd juː hæv dʌn/","tip":"Common reflection question"}],
        {"watch":["About Time — changing the past theme"],"listen":["Adele — Someone Like You"],"read":["FCE Use of English — conditionals"]},
        ["What would they have done?","What regret is expressed?","Did the past event really happen?","What wouldn't have happened?","Does if-clause use had + V3?"],
        ["Напиши 4 third conditional о прошлом году.","Объясни: If I had… I would have…","Перефразируй сожаление в third conditional."],
    ),
    43: _L(
        "Wish and if only",
        "Express wishes about present and regrets about the past.",
        ["What do you wish you could change now?", "What do you wish you had learned earlier?", "If only I had more free time!"],
        [{"en":"wish","ru":"желать"},{"en":"if only","ru":"если бы только"},{"en":"regret","ru":"сожалеть"},{"en":"present","ru":"настоящее"},{"en":"past","ru":"прошлое"},{"en":"change","ru":"изменить"},{"en":"sooner","ru":"раньше"},{"en":"luck","ru":"удача"},{"en":"complain","ru":"жаловаться"},{"en":"reality","ru":"реальность"}],
        "Wish & if only",
        [{"title":"Present wish","desc":"I wish + past simple (unreal present). I wish I had more time.","example":"I wish I spoke English better."},{"title":"Past regret","desc":"I wish + past perfect. If only I had studied harder!","example":"I wish I had taken that job."}],
        ["I wish + past (present unreal)","I wish + past perfect (past regret)"],
        {"wrong":"I wish I can fly.","right":"I wish I could fly."},
        [{"sentence":"I wish I ___ more time.","options":["had","have"],"answer":"had"},{"sentence":"She wishes she ___ harder.","options":["had studied","studied"],"answer":"had studied"},{"sentence":"If only it ___ stop raining!","options":["would","will"],"answer":"would"},{"sentence":"I wish I ___ to Paris.","options":["could go","can go"],"answer":"could go"},{"sentence":"He wishes he ___ that mistake.","options":["hadn't made","didn't make"],"answer":"hadn't made"}],
        [{"phrase":"I wish I had more time.","ipa":"/aɪ wɪʃ aɪ hæd mɔː taɪm/","tip":"Wish + past for present"},{"phrase":"If only I had known!","ipa":"/ɪf əʊnli aɪ hæd nəʊn/","tip":"If only — stronger wish"},{"phrase":"I wish I could help.","ipa":"/aɪ wɪʃ aɪ kʊd help/","tip":"Could — unreal ability"},{"phrase":"She wishes she lived abroad.","ipa":"/ʃiː wɪʃɪz ʃiː lɪvd əˈbrɔːd/","tip":"Lived — past form"},{"phrase":"I wish it would stop.","ipa":"/aɪ wɪʃ ɪt wʊd stɒp/","tip":"Would — wish for change"}],
        {"watch":["The Pursuit of Happyness — wishes and regrets"],"listen":["R.E.M. — Everybody Hurts"],"read":["English Grammar in Use — wish"]},
        ["What does the speaker wish for?","Is it about present or past?","What do they regret?","What would they change if only…?","Does wish use past tense?"],
        ["Напиши 3 I wish… о настоящем.","Напиши 3 I wish I had… о прошлом.","Перефразируй жалобу через I wish."],
    ),
    44: _L(
        "Causative have/get",
        "Say someone else does a service for you with have/get something done.",
        ["When did you last have your hair cut?", "Have you ever had your car repaired abroad?", "Where do you get your clothes cleaned?"],
        [{"en":"have done","ru":"сделать (через кого-то)"},{"en":"get done","ru":"сделать (разг.)"},{"en":"repair","ru":"ремонтировать"},{"en":"service","ru":"услуга"},{"en":"haircut","ru":"стрижка"},{"en":"clean","ru":"чистить"},{"en":"paint","ru":"красить"},{"en":"deliver","ru":"доставлять"},{"en":"install","ru":"устанавливать"},{"en":"fix","ru":"чинить"}],
        "Causative",
        [{"title":"Have something done","desc":"Have + object + past participle. Someone does it for you.","example":"I had my hair cut yesterday."},{"title":"Get something done","desc":"Get + object + past participle — more informal.","example":"I need to get my phone fixed."}],
        ["have/get + object + V3","have someone do something (active causative)"],
        {"wrong":"I cut my hair yesterday at the salon.","right":"I had my hair cut yesterday."},
        [{"sentence":"I need to ___ my car repaired.","options":["have","having"],"answer":"have"},{"sentence":"She got her house ___.","options":["painted","paint"],"answer":"painted"},{"sentence":"Where do you ___ your hair cut?","options":["have","has"],"answer":"have"},{"sentence":"We had the windows ___.","options":["cleaned","clean"],"answer":"cleaned"},{"sentence":"He is having his suit ___.","options":["delivered","deliver"],"answer":"delivered"}],
        [{"phrase":"I had my hair cut.","ipa":"/aɪ hæd maɪ heə kʌt/","tip":"Had + object + cut"},{"phrase":"I need to get it fixed.","ipa":"/aɪ niːd tə ɡet ɪt fɪkst/","tip":"Get it fixed — informal"},{"phrase":"She had her house painted.","ipa":"/ʃiː hæd hɜː haʊs peɪntɪd/","tip":"Painted — past participle"},{"phrase":"Where do you have it done?","ipa":"/weə də juː hæv ɪt dʌn/","tip":"Have it done — question"},{"phrase":"We're having the car serviced.","ipa":"/wɪə ˈhævɪŋ ðə kɑː ˈsɜːvɪst/","tip":"Present causative"}],
        {"watch":["Queer Eye — makeover services"],"listen":["Barbra Streisand — Woman in Love"],"read":["English Vocabulary in Use B1 — causative"]},
        ["What service did they have done?","Who did the work for them?","What needs to get fixed?","Where do they have their hair cut?","Have or get — which is used?"],
        ["Опиши 4 услуги через have/get something done.","Спроси: Have you ever had your…?","Сравни: I cut it myself vs I had it cut."],
    ),
    45: _L(
        "Passive across tenses",
        "Use passive voice in different tenses naturally.",
        ["What is being built in your area?", "Has the report been finished yet?", "What languages were spoken at the meeting?"],
        [{"en":"being","ru":"being (процесс)"},{"en":"been","ru":"been (завершённость)"},{"en":"published","ru":"опубликованный"},{"en":"announced","ru":"объявленный"},{"en":"completed","ru":"завершённый"},{"en":"discussed","ru":"обсуждаемый"},{"en":"issued","ru":"выпущенный"},{"en":"cancelled","ru":"отменённый"},{"en":"delayed","ru":"задержанный"},{"en":"approved","ru":"одобренный"}],
        "Passive (all tenses)",
        [{"title":"Tense forms","desc":"is done / was done / has been done / will be done / is being done","example":"The road is being repaired."},{"title":"By-agent","desc":"Optional by-phrase when agent matters.","example":"The decision was announced by the CEO."}],
        ["tense of be + V3","has/have been + V3 (perfect passive)"],
        {"wrong":"The letter has sent.","right":"The letter has been sent."},
        [{"sentence":"The bridge ___ repaired now.","options":["is being","is been"],"answer":"is being"},{"sentence":"The results ___ announced yesterday.","options":["were","was"],"answer":"were"},{"sentence":"Has the email ___ yet?","options":["been sent","sent"],"answer":"been sent"},{"sentence":"The book will ___ next month.","options":["be published","publish"],"answer":"be published"},{"sentence":"English ___ all over the world.","options":["is spoken","speaks"],"answer":"is spoken"}],
        [{"phrase":"It is being built.","ipa":"/ɪt ɪz ˈbiːɪŋ bɪlt/","tip":"Being + V3 — in progress"},{"phrase":"It has been sent.","ipa":"/ɪt hæz biːn sent/","tip":"Has been — present perfect passive"},{"phrase":"It was announced yesterday.","ipa":"/ɪt wɒz əˈnaʊnst ˈjestədeɪ/","tip":"Was + V3 — past"},{"phrase":"It will be completed soon.","ipa":"/ɪt wɪl biː kəmˈpliːtɪd suːn/","tip":"Will be — future passive"},{"phrase":"The meeting was cancelled.","ipa":"/ðə ˈmiːtɪŋ wɒz ˈkænsld/","tip":"Cancelled — double l BrE"}],
        {"watch":["BBC News — passive in headlines"],"listen":["Radiohead — Karma Police"],"read":["Financial Times — news passives B1"]},
        ["What is being done now?","What was announced?","Has it been completed?","What will be published?","Who was it done by?"],
        ["Преобразуй 5 активных в passive (разные времена).","Опиши новость в passive voice.","Ответь: Has it been finished yet?"],
    ),
    46: _L(
        "Narrative tenses",
        "Tell stories mixing past simple, past continuous, and past perfect.",
        ["Tell me about a time you arrived somewhere late.", "What had happened before the story started?", "What were you doing when something surprising happened?"],
        [{"en":"narrative","ru":"повествование"},{"en":"flashback","ru":"флешбэк"},{"en":"background","ru":"фон"},{"en":"sequence","ru":"последовательность"},{"en":"suddenly","ru":"внезапно"},{"en":"meanwhile","ru":"тем временем"},{"en":"earlier","ru":"раньше"},{"en":"already","ru":"уже"},{"en":"by then","ru":"к тому времени"},{"en":"afterwards","ru":"после"}],
        "Narrative tenses",
        [{"title":"Past simple","desc":"Main events in order.","example":"I arrived at the station and realised I had forgotten my ticket."},{"title":"Past perfect","desc":"Earlier background before another past action.","example":"She had already left when I called."}],
        ["Past simple — main events","Past continuous — background","Past perfect — earlier past"],
        {"wrong":"When I arrived, she already left.","right":"When I arrived, she had already left."},
        [{"sentence":"I ___ TV when he called.","options":["was watching","watched"],"answer":"was watching"},{"sentence":"She ___ before we arrived.","options":["had left","left"],"answer":"had left"},{"sentence":"They ___ the news and went home.","options":["heard","were hearing"],"answer":"heard"},{"sentence":"By then, I ___ my keys.","options":["had lost","lost"],"answer":"had lost"},{"sentence":"What ___ you doing at eight?","options":["were","was"],"answer":"were"}],
        [{"phrase":"I had already eaten.","ipa":"/aɪ hæd ɔːlˈredi ˈiːtn/","tip":"Past perfect — before past"},{"phrase":"I was waiting outside.","ipa":"/aɪ wɒz ˈweɪtɪŋ aʊtˈsaɪd/","tip":"Past continuous — background"},{"phrase":"Suddenly, the phone rang.","ipa":"/ˈsʌdnli ðə fəʊn ræŋ/","tip":"Suddenly — story turning point"},{"phrase":"By then, he had left.","ipa":"/baɪ ðen hiː hæd left/","tip":"By then + past perfect"},{"phrase":"Meanwhile, it was raining.","ipa":"/ˈmiːnwaɪl ɪt wɒz ˈreɪnɪŋ/","tip":"Meanwhile — parallel action"}],
        {"watch":["Sherlock — narrative flashbacks"],"listen":["The Beatles — A Day in the Life"],"read":["Graded reader — short stories B1"]},
        ["What happened first?","What had already happened?","What was happening in the background?","When did the main event occur?","What happened afterwards?"],
        ["Расскажи историю: 6 предложений, 3 времени.","Используй suddenly / meanwhile / by then.","Опиши опоздание: past perfect + past simple."],
    ),
    47: _L(
        "Giving advice",
        "Give recommendations with should, ought to, and had better.",
        ["What should tourists do in your city?", "What ought people to do to stay healthy?", "What should you not do at work?"],
        [{"en":"should","ru":"следует"},{"en":"ought to","ru":"следовало бы"},{"en":"had better","ru":"лучше бы"},{"en":"advice","ru":"совет"},{"en":"recommend","ru":"рекомендовать"},{"en":"suggest","ru":"предлагать"},{"en":"healthy","ru":"здоровый"},{"en":"avoid","ru":"избегать"},{"en":"warning","ru":"предупреждение"},{"en":"responsible","ru":"ответственный"}],
        "Giving advice",
        [{"title":"Should / ought to","desc":"General advice: You should rest. You ought to see a doctor.","example":"You should drink more water."},{"title":"Had better","desc":"Strong advice or warning: You'd better hurry!","example":"You'd better not be late."}],
        ["should/ought to + V1","had better (+ not) + V1"],
        {"wrong":"You should to go home.","right":"You should go home."},
        [{"sentence":"You ___ see a doctor.","options":["should","should to"],"answer":"should"},{"sentence":"She ought ___ more sleep.","options":["to get","get"],"answer":"to get"},{"sentence":"We'd better ___ now.","options":["leave","to leave"],"answer":"leave"},{"sentence":"You shouldn't ___ so much sugar.","options":["eat","eating"],"answer":"eat"},{"sentence":"He had better ___ careful.","options":["be","being"],"answer":"be"}],
        [{"phrase":"You should rest.","ipa":"/juː ʃʊd rest/","tip":"Should + base verb, no to"},{"phrase":"You ought to try it.","ipa":"/juː ɔːt tə traɪ ɪt/","tip":"Ought to — formal advice"},{"phrase":"You'd better hurry.","ipa":"/juːd ˈbetə ˈhʌri/","tip":"Had better — warning"},{"phrase":"I suggest taking a break.","ipa":"/aɪ səˈdʒest ˈteɪkɪŋ ə breɪk/","tip":"Suggest + -ing"},{"phrase":"You shouldn't worry.","ipa":"/juː ˈʃʊdnt ˈwʌri/","tip":"Shouldn't — negative advice"}],
        {"watch":["Doctor Who — giving advice scenes"],"listen":["Bob Marley — Three Little Birds"],"read":["NHS — health advice leaflets"]},
        ["What should the character do?","What ought they to avoid?","Is had better a warning?","What does the doctor recommend?","What suggestion is made?"],
        ["Дай 5 советов туристу в твоём городе.","Предупреди друга: You'd better…","Перефразируй советы в ought to / should."],
    ),
    48: _L(
        "Technology and digital life",
        "Discuss apps, devices, and online habits in natural English.",
        ["How much time do you spend on your phone?", "What apps do you use every day?", "How has technology changed your work or study?"],
        [{"en":"device","ru":"устройство"},{"en":"app","ru":"приложение"},{"en":"online","ru":"онлайн"},{"en":"password","ru":"пароль"},{"en":"update","ru":"обновление"},{"en":"download","ru":"скачивать"},{"en":"stream","ru":"стримить"},{"en":"privacy","ru":"конфиденциальность"},{"en":"battery","ru":"батарея"},{"en":"notification","ru":"уведомление"}],
        "Technology",
        [{"title":"Daily tech","desc":"I use my phone to… / I spend time on social media.","example":"I check my emails on my phone every morning."},{"title":"Changes","desc":"Present perfect for changes: Technology has changed how we work.","example":"Streaming has replaced DVDs for many people."}],
        ["I use + device to + V","Technology has changed + noun","spend time on + app/site"],
        {"wrong":"I am use my laptop every day.","right":"I use my laptop every day."},
        [{"sentence":"I ___ my phone too much.","options":["use","am use"],"answer":"use"},{"sentence":"Have you ___ the latest update?","options":["downloaded","download"],"answer":"downloaded"},{"sentence":"She spends hours ___ videos.","options":["watching","to watch"],"answer":"watching"},{"sentence":"Technology has ___ our lives.","options":["changed","change"],"answer":"changed"},{"sentence":"Don't forget your ___.","options":["password","passwords"],"answer":"password"}],
        [{"phrase":"I need to charge my phone.","ipa":"/aɪ niːd tə tʃɑːdʒ maɪ fəʊn/","tip":"Charge — battery vocabulary"},{"phrase":"I spend too much time online.","ipa":"/aɪ spend tuː mʌtʃ taɪm ˈɒnlaɪn/","tip":"Spend time on — digital habits"},{"phrase":"Have you updated the app?","ipa":"/hæv juː ʌpˈdeɪtɪd ði æp/","tip":"Update — tech verb"},{"phrase":"My battery is low.","ipa":"/maɪ ˈbætəri ɪz ləʊ/","tip":"Battery low — everyday phrase"},{"phrase":"Technology has changed everything.","ipa":"/tekˈnɒlədʒi hæz tʃeɪndʒd ˈevriθɪŋ/","tip":"Present perfect for change"}],
        {"watch":["Black Mirror — technology themes (selected episodes)"],"listen":["Daft Punk — Technologic"],"read":["Wired — easy tech articles"]},
        ["What device do they use?","How much time do they spend online?","What app is mentioned?","How has technology changed something?","What problem do they mention?"],
        ["Опиши свой digital day — 5 предложений.","Сравни life before/after smartphones.","Дай 3 tech tips a friend should follow."],
    ),
})

# ── B2 filler 57–64 ──
FILLER.update({
    57: _L(
        "Mixed conditionals",
        "Connect past conditions with present results, and vice versa.",
        ["If you had studied medicine, what would you do now?", "If I were braver, I would have spoken up yesterday.", "How would your life be different if you had moved abroad?"],
        [{"en":"mixed","ru":"смешанный"},{"en":"consequence","ru":"следствие"},{"en":"regret","ru":"сожаление"},{"en":"present result","ru":"результат в настоящем"},{"en":"past cause","ru":"причина в прошлом"},{"en":"hypothetical","ru":"гипотетический"},{"en":"otherwise","ru":"иначе"},{"en":"now","ru":"сейчас"},{"en":"then","ru":"тогда"},{"en":"outcome","ru":"исход"}],
        "Mixed conditionals",
        [{"title":"Past → present","desc":"If + past perfect, would + verb (now).","example":"If I had taken that job, I would be living in Berlin now."},{"title":"Present → past","desc":"If + past simple, would have + V3.","example":"If I were more careful, I wouldn't have lost the keys."}],
        ["If + had + V3, would + V1 (now)","If + past, would have + V3"],
        {"wrong":"If I studied harder, I would be passed.","right":"If I had studied harder, I would have passed."},
        [{"sentence":"If she had left earlier, she ___ be here now.","options":["would","will"],"answer":"would"},{"sentence":"If I were taller, I ___ have joined the team.","options":["would","would have"],"answer":"would have"},{"sentence":"If they had invested, they ___ rich now.","options":["would be","will be"],"answer":"would be"},{"sentence":"If he knew the truth, he ___ differently.","options":["would have acted","would act"],"answer":"would have acted"},{"sentence":"If I had saved money, I ___ buy a flat now.","options":["could","could have"],"answer":"could"}],
        [{"phrase":"If I had known, I would be happier now.","ipa":"/ɪf aɪ hæd nəʊn aɪ wʊd biː ˈhæpiə naʊ/","tip":"Past condition → present result"},{"phrase":"If I were you, I would have accepted.","ipa":"/ɪf aɪ wə juː aɪ wʊd hæv əkˈseptɪd/","tip":"Present state → past result"},{"phrase":"If she had moved, she would live abroad.","ipa":"/ɪf ʃiː hæd muːvd ʃiː wʊd lɪv əˈbrɔːd/","tip":"Mixed conditional chain"},{"phrase":"What would you do now if…?","ipa":"/wɒt wʊd juː duː naʊ ɪf/","tip":"Now — present result marker"},{"phrase":"I wouldn't have failed if I were more disciplined.","ipa":"/aɪ ˈwʊdnt hæv feɪld ɪf aɪ wə mɔː ˈdɪsəplɪnd/","tip":"Character trait → past outcome"}],
        {"watch":["The Butterfly Effect — mixed outcomes"],"listen":["Coldplay — The Scientist"],"read":["Advanced Grammar in Use — mixed conditionals"]},
        ["What present result comes from a past condition?","What past outcome comes from a present trait?","Is the situation real?","Which time does each clause refer to?","What would be different now?"],
        ["Напиши 3 mixed conditionals (past→present).","Напиши 2 mixed (present→past).","Объясни разницу 2nd vs 3rd vs mixed."],
    ),
    58: _L(
        "Subjunctive and formal English",
        "Use formal structures in requests, recommendations, and fixed phrases.",
        ["I suggest that he be on time — does that sound formal?", "It is essential that she attend the meeting.", "How do you write a formal recommendation?"],
        [{"en":"subjunctive","ru":"сослагательное наклонение"},{"en":"essential","ru":"необходимый"},{"en":"recommend","ru":"рекомендовать"},{"en":"insist","ru":"настаивать"},{"en":"propose","ru":"предлагать"},{"en":"formal","ru":"формальный"},{"en":"mandatory","ru":"обязательный"},{"en":"attend","ru":"присутствовать"},{"en":"present","ru":"представлять"},{"en":"hereby","ru":"настоящим"}],
        "Subjunctive & formal",
        [{"title":"Mandative subjunctive","desc":"suggest/recommend/insist + that + base verb (no -s).","example":"I suggest that he be present."},{"title":"Fixed formal phrases","desc":"God save the Queen. Be that as it may.","example":"It is vital that every student submit the form."}],
        ["that + base verb (subjunctive)","It is + adjective + that + base verb"],
        {"wrong":"I suggest that he is on time.","right":"I suggest that he be on time."},
        [{"sentence":"I recommend that she ___ early.","options":["arrive","arrives"],"answer":"arrive"},{"sentence":"It is essential that he ___ informed.","options":["be","is"],"answer":"be"},{"sentence":"They insisted that we ___ on time.","options":["be","are"],"answer":"be"},{"sentence":"It is important that she ___ the rules.","options":["follow","follows"],"answer":"follow"},{"sentence":"I propose that the matter ___ discussed.","options":["be","is"],"answer":"be"}],
        [{"phrase":"I suggest that he be present.","ipa":"/aɪ səˈdʒest ðæt hiː biː ˈpreznt/","tip":"Be — subjunctive, not is"},{"phrase":"It is vital that she attend.","ipa":"/ɪt ɪz ˈvaɪtl ðæt ʃiː əˈtend/","tip":"Attend — no -s"},{"phrase":"We insist that they comply.","ipa":"/wiː ɪnˈsɪst ðæt ðeɪ kəmˈplaɪ/","tip":"Formal compliance language"},{"phrase":"Be that as it may.","ipa":"/biː ðæt əz ɪt meɪ/","tip":"Fixed formal phrase"},{"phrase":"I hereby confirm receipt.","ipa":"/aɪ hɪəˈbaɪ kənˈfɜːm rɪˈsiːt/","tip":"Business formal register"}],
        {"watch":["The Crown — formal speech"],"listen":["BBC Radio 4 — formal announcements"],"read":["Formal letter samples B2"]},
        ["What subjunctive form is used after suggest?","Is the tone formal or informal?","What does insist that… mean?","Find a fixed formal phrase.","How is the recommendation phrased?"],
        ["Перепиши 4 предложения в formal subjunctive.","Сравни: I suggest he is vs I suggest he be.","Напиши formal recommendation paragraph."],
    ),
    59: _L(
        "Critical writing",
        "Analyse texts and express evaluation in academic style.",
        ["How do you structure a critical review?", "What evidence supports the author's argument?", "How do you express agreement and disagreement in an essay?"],
        [{"en":"analyse","ru":"анализировать"},{"en":"evaluate","ru":"оценивать"},{"en":"argument","ru":"аргумент"},{"en":"evidence","ru":"доказательство"},{"en":"claim","ru":"утверждение"},{"en":"counterargument","ru":"контраргумент"},{"en":"bias","ru":"предвзятость"},{"en":"assumption","ru":"допущение"},{"en":"conclude","ru":"заключать"},{"en":"criticise","ru":"критиковать"}],
        "Critical writing",
        [{"title":"Structure","desc":"Introduce the text → summarise → evaluate → conclude.","example":"The author claims that… However, the evidence is limited."},{"title":"Evaluation language","desc":"The argument is convincing / weak / one-sided.","example":"While the article raises valid points, it overlooks key data."}],
        ["The author claims/argues that…","The evidence suggests…","However, / Nevertheless,"],
        {"wrong":"The author is wrong and stupid.","right":"The author's argument is unconvincing because…"},
        [{"sentence":"The author ___ that technology improves learning.","options":["claims","claim"],"answer":"claims"},{"sentence":"The evidence is ___.","options":["limited","limit"],"answer":"limited"},{"sentence":"___, the conclusion is too general.","options":["However","Although"],"answer":"However"},{"sentence":"She ___ the main assumptions.","options":["questions","question"],"answer":"questions"},{"sentence":"In ___, the text is thought-provoking.","options":["conclusion","conclude"],"answer":"conclusion"}],
        [{"phrase":"The author argues that…","ipa":"/ði ˈɔːθə ˈɑːɡjuːz ðæt/","tip":"Academic reporting verb"},{"phrase":"The evidence is limited.","ipa":"/ði ˈevɪdəns ɪz ˈlɪmɪtɪd/","tip":"Measured criticism"},{"phrase":"Nevertheless, it is worth reading.","ipa":"/ˌnevəðəˈles ɪt ɪz wɜːθ ˈriːdɪŋ/","tip":"Nevertheless — formal contrast"},{"phrase":"This raises important questions.","ipa":"/ðɪs reɪzɪz ɪmˈpɔːtnt ˈkwestʃənz/","tip":"Raises — academic collocation"},{"phrase":"On balance, the review is fair.","ipa":"/ɒn ˈbæləns ðə rɪˈvjuː ɪz feə/","tip":"On balance — evaluation phrase"}],
        {"watch":["TED-Ed — how to analyse arguments"],"listen":["BBC Arts — book reviews"],"read":["The Guardian — review section"]},
        ["What does the author claim?","Is the evidence strong or weak?","What counterargument appears?","How does the reviewer evaluate the text?","What is the final conclusion?"],
        ["Напиши critical paragraph о статье (120 слов).","Используй claims, however, evidence.","Оцени аргумент: convincing or weak?"],
    ),
    60: _L(
        "Nuanced modals",
        "Express probability and criticism with advanced modal verbs.",
        ["What might have happened if they had left earlier?", "She must have forgotten — what does that mean?", "How do you criticise past behaviour politely?"],
        [{"en":"might have","ru":"возможно (прошлое)"},{"en":"must have","ru":"должно быть (вывод)"},{"en":"could have","ru":"мог бы (прошлое)"},{"en":"should have","ru":"следовало бы"},{"en":"needn't have","ru":"необязательно было"},{"en":"deduction","ru":"вывод"},{"en":"probability","ru":"вероятность"},{"en":"criticism","ru":"критика"},{"en":"speculate","ru":"предполагать"},{"en":"certainty","ru":"уверенность"}],
        "Nuanced modals",
        [{"title":"Past deduction","desc":"must have + V3 (near certainty). might/could have + V3 (possibility).","example":"She must have left already."},{"title":"Past criticism","desc":"should have + V3. needn't have + V3 (unnecessary action).","example":"You should have told me earlier."}],
        ["must/might/could + have + V3","should/shouldn't have + V3"],
        {"wrong":"She must left already.","right":"She must have left already."},
        [{"sentence":"She ___ have forgotten. (I'm almost sure)","options":["must","might"],"answer":"must"},{"sentence":"He ___ have missed the train. (possible)","options":["could","must"],"answer":"could"},{"sentence":"You ___ have called me!","options":["should","should to"],"answer":"should"},{"sentence":"We ___ have bought so much food. (unnecessary)","options":["needn't","mustn't"],"answer":"needn't"},{"sentence":"They ___ have arrived by now.","options":["should","should to"],"answer":"should"}],
        [{"phrase":"She must have forgotten.","ipa":"/ʃiː mʌst hæv fəˈɡɒtn/","tip":"Must have — deduction"},{"phrase":"It might have been a mistake.","ipa":"/ɪt maɪt hæv biːn ə mɪˈsteɪk/","tip":"Might have — possibility"},{"phrase":"You should have told me.","ipa":"/juː ʃʊd hæv təʊld miː/","tip":"Should have — criticism"},{"phrase":"We needn't have worried.","ipa":"/wiː ˈniːdnt hæv ˈwʌrid/","tip":"Needn't have — unnecessary"},{"phrase":"They could have taken a taxi.","ipa":"/ðeɪ kʊd hæv ˈteɪkn ə ˈtæksi/","tip":"Could have — alternative past"}],
        {"watch":["Sherlock — deduction scenes"],"listen":["Podcast — crime speculation"],"read":["Murphy — modals of deduction"]},
        ["What deduction does the speaker make?","Is must have or might have used?","What criticism is expressed?","Was the action necessary?","What could have happened instead?"],
        ["Объясни разницу must have vs might have.","Напиши 4 предложения с should have.","Опиши ситуацию с needn't have."],
    ),
    61: _L(
        "Media English",
        "Understand news headlines, reports, and broadcast language.",
        ["How do headlines differ from full sentences?", "What does 'alleged' mean in news?", "How do reporters attribute information?"],
        [{"en":"headline","ru":"заголовок"},{"en":"report","ru":"репортаж"},{"en":"source","ru":"источник"},{"en":"alleged","ru":"предполагаемый"},{"en":"according to","ru":"согласно"},{"en":"breaking","ru":"срочный"},{"en":"coverage","ru":"освещение"},{"en":"quote","ru":"цитата"},{"en":"broadcast","ru":"трансляция"},{"en":"witness","ru":"свидетель"}],
        "Media English",
        [{"title":"Headlines","desc":"Omitted articles, present simple for past: PM visits Paris.","example":"Markets fall as inflation rises."},{"title":"Attribution","desc":"According to… / Sources say… / Alleged + noun.","example":"According to officials, the plan will be announced today."}],
        ["Headline: noun phrases, present tense","According to + source + clause"],
        {"wrong":"According the report, it is true.","right":"According to the report, it is true."},
        [{"sentence":"Markets ___ after the announcement. (headline style)","options":["fall","fell"],"answer":"fall"},{"sentence":"___ to police, two people were injured.","options":["According","According to"],"answer":"According to"},{"sentence":"The ___ suspect was arrested.","options":["alleged","allegedly"],"answer":"alleged"},{"sentence":"Sources ___ the deal is close.","options":["say","says"],"answer":"say"},{"sentence":"Breaking ___ : summit begins.","options":["news","new"],"answer":"news"}],
        [{"phrase":"Markets fall on inflation fears.","ipa":"/ˈmɑːkɪts fɔːl ɒn ɪnˈfleɪʃn fɪəz/","tip":"Headline — present tense"},{"phrase":"According to officials…","ipa":"/əˈkɔːdɪŋ tə əˈfɪʃlz/","tip":"According to — attribution"},{"phrase":"The alleged attack…","ipa":"/ði əˈledʒd əˈtæk/","tip":"Alleged — not yet proven"},{"phrase":"Breaking news.","ipa":"/ˈbreɪkɪŋ njuːz/","tip":"Fixed media phrase"},{"phrase":"Sources say that…","ipa":"/ˈsɔːsɪz seɪ ðæt/","tip":"Indirect reporting"}],
        {"watch":["BBC News — 6 o'clock bulletin"],"listen":["NPR — hourly news summary"],"read":["Reuters — headline practice"]},
        ["What does the headline omit?","Who is the source?","What does alleged mean here?","Is it breaking news?","How is information attributed?"],
        ["Перепиши 4 headlines как полные предложения.","Найди according to / sources say в тексте.","Объясни значение alleged."],
    ),
    62: _L(
        "Negotiation English",
        "Make proposals, counter-offers, and close deals professionally.",
        ["How do you open a business negotiation?", "What phrases soften a counter-offer?", "How do you agree on terms politely?"],
        [{"en":"offer","ru":"предложение"},{"en":"counter-offer","ru":"встречное предложение"},{"en":"terms","ru":"условия"},{"en":"deadline","ru":"срок"},{"en":"compromise","ru":"компромисс"},{"en":"deal","ru":"сделка"},{"en":"proposal","ru":"предложение"},{"en":"accept","ru":"принимать"},{"en":"reject","ru":"отклонять"},{"en":"finalize","ru":"завершать"}],
        "Negotiation",
        [{"title":"Opening & proposing","desc":"We'd like to propose… / Our initial offer is…","example":"We'd like to propose a partnership."},{"title":"Counter-offers","desc":"Would you consider…? / We could meet you halfway.","example":"Could you lower the price by ten percent?"}],
        ["We'd like to propose…","Would you consider + noun/-ing?","Let's finalize the terms."],
        {"wrong":"Give me a better price now.","right":"Would you consider a lower price?"},
        [{"sentence":"We'd like to ___ a deal.","options":["finalize","final"],"answer":"finalize"},{"sentence":"___ you consider a discount?","options":["Would","Do"],"answer":"Would"},{"sentence":"Our ___ offer is €10,000.","options":["initial","initiate"],"answer":"initial"},{"sentence":"Let's meet ___.","options":["halfway","half"],"answer":"halfway"},{"sentence":"We can't ___ those terms.","options":["accept","accepting"],"answer":"accept"}],
        [{"phrase":"We'd like to propose a deal.","ipa":"/wiːd laɪk tə prəˈpəʊz ə diːl/","tip":"Propose — formal offer"},{"phrase":"Would you consider a discount?","ipa":"/wʊd juː kənˈsɪdə ə ˈdɪskaʊnt/","tip":"Soften with would you"},{"phrase":"Let's meet halfway.","ipa":"/lets miːt ˈhɑːfweɪ/","tip":"Compromise phrase"},{"phrase":"We can accept those terms.","ipa":"/wiː kən əkˈsept ðəʊz tɜːmz/","tip":"Accept terms — collocation"},{"phrase":"Can we finalize today?","ipa":"/kən wiː ˈfaɪnəlaɪz təˈdeɪ/","tip":"Finalize — close the deal"}],
        {"watch":["Shark Tank — negotiation clips"],"listen":["HBR IdeaCast — deal-making"],"read":["Business English — negotiation phrases"]},
        ["What is the initial offer?","What counter-offer is made?","Do they reach a compromise?","What terms are discussed?","How do they close the deal?"],
        ["Сыграй переговоры: offer → counter-offer → deal.","Напиши 5 softening phrases для бизнеса.","Перефразируй грубое предложение вежливо."],
    ),
    63: _L(
        "Presentations",
        "Structure and deliver clear presentations in English.",
        ["How do you open a presentation?", "What phrases introduce the next slide?", "How do you handle questions at the end?"],
        [{"en":"introduce","ru":"представлять"},{"en":"outline","ru":"план"},{"en":"slide","ru":"слайд"},{"en":"audience","ru":"аудитория"},{"en":"handout","ru":"раздаточный материал"},{"en":"Q&A","ru":"вопросы и ответы"},{"en":"summarise","ru":"подводить итог"},{"en":"engage","ru":"вовлекать"},{"en":"clarify","ru":"уточнять"},{"en":"feedback","ru":"обратная связь"}],
        "Presentations",
        [{"title":"Structure","desc":"Good morning → outline → sections → summary → Q&A.","example":"Today I'll talk about three main points."},{"title":"Signposting","desc":"Moving on to… / Let me clarify… / To sum up…","example":"Let's move on to the next slide."}],
        ["Today I'll talk about…","Moving on to…","To sum up… / In conclusion…"],
        {"wrong":"I talk about three point today.","right":"Today I'll talk about three points."},
        [{"sentence":"Today I'll ___ three topics.","options":["cover","covering"],"answer":"cover"},{"sentence":"Let's move ___ to the next point.","options":["on","in"],"answer":"on"},{"sentence":"To ___ up, the data shows growth.","options":["sum","summarise"],"answer":"sum"},{"sentence":"Are there any ___?","options":["questions","question"],"answer":"questions"},{"sentence":"Let me ___ that.","options":["clarify","clarifying"],"answer":"clarify"}],
        [{"phrase":"Good morning, everyone.","ipa":"/ɡʊd ˈmɔːnɪŋ ˈevriwʌn/","tip":"Standard opening"},{"phrase":"Today I'll cover three points.","ipa":"/təˈdeɪ aɪl ˈkʌvə θriː pɔɪnts/","tip":"Cover — presentation verb"},{"phrase":"Moving on to the next slide.","ipa":"/ˈmuːvɪŋ ɒn tə ðə nekst slaɪd/","tip":"Signposting phrase"},{"phrase":"To sum up…","ipa":"/tə sʌm ʌp/","tip":"Summary marker"},{"phrase":"Thank you for your attention.","ipa":"/θæŋk juː fɔː jɔː əˈtenʃn/","tip":"Polite closing"}],
        {"watch":["TED Talks — presentation openings"],"listen":["Apple keynote clips"],"read":["Presentation Phrases B2 workbook"]},
        ["How does the speaker open?","What signposting phrases are used?","How many main points are covered?","How do they summarise?","How is Q&A handled?"],
        ["Подготовь outline презентации на 3 пункта.","Запиши opening + closing (30 секунд).","Используй 5 signposting phrases."],
    ),
    64: _L(
        "B2 mastery review",
        "Consolidate B2 skills and exam strategies across the course.",
        ["Which B2 exam are you preparing for?", "What reading strategy do you use first?", "Which grammar topics do you want to review?"],
        [{"en":"review","ru":"повторение"},{"en":"strategy","ru":"стратегия"},{"en":"skim","ru":"бегло просматривать"},{"en":"scan","ru":"искать информацию"},{"en":"assessment","ru":"оценка"},{"en":"proficiency","ru":"владение"},{"en":"certificate","ru":"сертификат"},{"en":"checklist","ru":"чеклист"},{"en":"timing","ru":"тайминг"},{"en":"accuracy","ru":"точность"}],
        "B2 mastery",
        [{"title":"Exam skills","desc":"Skim for gist, scan for details. Manage time per task.","example":"Skim the title and first paragraph first."},{"title":"Grammar review","desc":"Conditionals, passive, modals, reported speech, linking words.","example":"Review one grammar topic per study session."}],
        ["Skim → main idea / Scan → details","Essay: introduction + body + conclusion"],
        {"wrong":"I read every word slowly in the exam.","right":"I skim first, then scan for answers."},
        [{"sentence":"To find a date quickly, you ___.","options":["scan","skim"],"answer":"scan"},{"sentence":"For the main idea, you ___.","options":["skim","scan"],"answer":"skim"},{"sentence":"B2 is ___ C1 on the CEFR scale.","options":["below","above"],"answer":"below"},{"sentence":"Start your essay with an ___.","options":["introduction","conclusion"],"answer":"introduction"},{"sentence":"Word formation is tested ___ B2 exams.","options":["in","on"],"answer":"in"}],
        [{"phrase":"Skim the text first.","ipa":"/skɪm ðə tekst fɜːst/","tip":"Skim — reading strategy"},{"phrase":"Scan for keywords.","ipa":"/skæn fɔː ˈkiːwɜːdz/","tip":"Scan — detail search"},{"phrase":"Manage your time.","ipa":"/ˈmænɪdʒ jɔː taɪm/","tip":"Exam timing advice"},{"phrase":"Check the word limit.","ipa":"/tʃek ðə wɜːd ˈlɪmɪt/","tip":"Writing task requirement"},{"phrase":"I'm preparing for FCE.","ipa":"/aɪm prɪˈpeərɪŋ fɔː ef siː iː/","tip":"FCE — B2 Cambridge exam"}],
        {"watch":["Cambridge B2 preparation webinars"],"listen":["FCE listening practice tests"],"read":["Official B2 sample papers"]},
        ["What exam is mentioned?","What is skim vs scan?","How should an essay start?","What grammar needs review?","What time strategy is recommended?"],
        ["Составь review checklist из 10 тем B2.","Напиши essay plan (4 paragraphs).","Объясни skim vs scan на примере."],
    ),
})
